src/core.js
src/templates/confirm_overwrite.html

So I attempted to do this as a PID on a flight. @orangejenny brought this up in her field report. No HQ changes necessary.
I also attempted to do some work on automatically merging conflicts: https://github.com/dimagi/Vellum/compare/concurrent-editors
While that works suprisingly ok for non conflicting changes, I had to fix enough malformed XML to not recommend merging that, but it may give a starting point.

Warn before overwriting work

---

Makefile

Not entirely certain why this wasn't done before, but after running `bower update` I'm getting 404's on the jquery-ui images when I load Vellum in HQ.
Related: I think these are the bower components that were updated on my machine when I ran `bower update`. Unfortunately it doesn't say what versions were in place before they were updated.
```
requirejs#2.1.15 bower_components/requirejs
sinonjs#1.10.2 bower_components/sinonjs
langcodes#4804f8f687 bower_components/langcodes
jsdiff#1.2.1 bower_components/jsdiff
requirejs-text#2.0.13 bower_components/requirejs-text
MediaUploader#170f4b63c7 bower_components/MediaUploader
requirejs-tpl#a3ca1e0e7f bower_components/requirejs-tpl
require-less#0.1.5 bower_components/require-less
require-css#0.1.8 bower_components/require-css
chai#1.10.0 …
```

Include jquery-ui theme images in build

---

Makefile

This should make it easier to tell when dependencies change, and possibly catch errors before they hit prod.
@emord

Add bower packages manifest to build output

---

src/uploader.js
test

Also remove filter from test script now that it's not needed.
There seems to be a timing bug with asynchronously loading the file-uploader component, which subsequently caused the destroy method to fail, breaking tests. This was only observed in my local environment. Other developers and Travis did not see the problem. The bug was uncovered by https://github.com/dimagi/Vellum/pull/303, which seems entirely unrelated.
@emord

Fix tests failing only in my local environment

---

src/intentManager.js
tests/intentManager.js
tests/main.js
tests/static/all_question_types.xml
tests/static/intentManager/intent-with-unknown-attrs.xml
tests/static/profiling/small-form.xml

This improves intent handling so Derek doesn't need to use ignore/retain anymore. See also [FB #149925](http://manage.dimagi.com/default.asp?149925).

Preserve unknown attributes on ODK intent

---

src/core.js
tests/javaRosa.js
tests/utils.js

http://manage.dimagi.com/default.asp?148701
Are there any (performance) reasons to be more surgical about this, rather than just refreshing the whole tree?

Show correct language when node is opened

---

src/form.js
src/util.js
tests/form.js

https://github.com/dimagi/Vellum/pull/335#issuecomment-75648494
This reverts commit 0d0d77aa67c0101b67ac3a9d8feae174e857801d, reversing
changes made to 31db9169118b02d2d2b58d23ad61d790d030c82a.
Conflicts:
tests/form.js

Revert "Merge pull request #335 from dimagi/repeat-count-reference"

---

src/uploader.js

http://manage.dimagi.com/default.asp?159721
FYI @emord, https://github.com/dimagi/Vellum/pull/346 was incomplete because it only fixed one of the `widget.getValue()` calls. `widget.getPlaceholder()` had an odor when I reviewed that PR, but I couldn't think of an easy better way. Turns out `widget.getItextValue()` is exactly what we needed.
The second commit is a test speed optimization, and is completely unrelated to the fix.

Use itext value instead of widget value/placeholder

---

src/tree.js
tests/writer.js

Shout out to @millerdev for this more intelligent fix. This is take 2 of https://github.com/dimagi/Vellum/pull/358
The solution is to remove node from the tree if it has a different root node from the current tree. This can happen if you try to create a new tree type with the same name as a previously used one. (like when you create data trees dynamically)
I still think a better solution is to create walkDataTree which never actually creates a new tree, but that's a little harder than initially thought.

Real fix save after delete

---

src/mugs.js
tests/javaRosa.js

Mobile ignores both help text and hint text for all kind of groups (base, repeat, and question list). Remove them from the Vellum UI.
Verified that old forms with help/hint text specified will work with the new code. Any old help/hint for groups will not be visible on the UI and will be removed from XML when the form is saved.

Hide hints and help for groups

---

src/javaRosa.js
src/less-style/question-props.less
src/widgets.js

The edit buttons for display/validation conditions, and the "auto?" checkboxes for various advanced properties, grab focus before their text boxes, which is annoying if you're tabbing through properties. It's easier to change the markup & styling than to futz with global tabindex.
Checked that this looks & behaves the same in Chrome, Firefox, Safari.

Fix tab order

---

src/core.js
src/javaRosa.js
tests/javaRosa.js
tests/static/javaRosa/group-with-constraint.xml

http://manage.dimagi.com/default.asp?164598
In certain forms, when constraint text changes and fireChangeEvents goes through all mugs to update any that share itext with the changed itext, ids are blank for both widget.getItextItem() and some other mug's labelItext...so a question-label-text-change event gets fired for that other mug, which causes  toggleConstraintItext to run, which updates the visibility of the currently-displayed validation message inputs based on the constraintMsgItext of this other mug, which isn't right.
I'm not clear on when it's expected for an itext id to be blank, and therefore not sure if this is a reasonable fix or a band-aid for a larger problem.

Validation message inputs disappearing

---

src/javaRosa.js
src/util.js
tests/javaRosa.js

http://manage.dimagi.com/default.asp?166079#925204
This was already enforced for labelItext, but it isn't checked for auto ids. (and probably shouldn't be. Those should generate valid labels)
On other mugs it is already enforced as you can't have an apostrophe in a node id.

Escape apostrophes in itext

---

src/core.js
src/exporter.js
src/form.js
src/javaRosa.js
src/mugs.js
src/parser.js
tests/core.js
tests/form.js
tests/javaRosa.js
tests/parser.js
tests/utils.js

Fix the labels on select choices, which did not work correctly because the itext widget uses the mug's `nodeID` property, and choices had their value in `defaultValue`. Been wanting to change that one for a while. http://manage.dimagi.com/default.asp?124210
Also [UserVoice](https://dimagi.uservoice.com/forums/176376-form-builder/suggestions/7672437-tab-key-action-in-form-builder).
Merging into copy-paste-dev because the `defaultValue` -> `nodeID` change is much easier since the duplicate question ID refactor.
@emord 
cc @benrudolph

Select text on tab into label widget

---

src/commtrack.js
tests/commtrack.js

http://manage.dimagi.com/default.asp?166979
`_.extend` is tricky. In this case it was mutating the first argument, which meant Balance's section data was getting Transfer's properties.
@orangejenny

Fix “Case” property not showing for Balance

---

src/core.js
src/form.js
src/ignoreButRetain.js
src/mugs.js
src/parser.js
src/writer.js
tests/formdesigner.ignoreButRetain.js
tests/static/ignoreButRetain/case-with-update.xml
tests/static/ignoreButRetain/common-ignored.xml
tests/static/ignoreButRetain/common.xml
tests/static/ignoreButRetain/delete-bug-after.xml
tests/static/ignoreButRetain/delete-bug-before.xml
tests/static/ignoreButRetain/ignore-in-head.xml
tests/static/ignoreButRetain/ignored-binds-with-extra-path.xml
tests/static/ignoreButRetain/ignored-control-node.xml
tests/static/ignoreButRetain/ignored-data-node.xml
tests/static/ignoreButRetain/ignored-tag-first.xml
tests/static/ignoreButRetain/multi-match.xml
tests/static/ignoreButRetain/multiple-ignores.xml
tests/static/ignoreButRetain/nested-ignored-nodes.xml
tests/static/ignoreButRetain/referenced-renamed.xml
tests/static/ignoreButRetain/referenced-unrenamed.xml
tests/static/ignoreButRetain/renamed.xml

This is a big overhaul of the ignore-but-retain plugin. It makes the plugin smarter about handling ignored things that look like questions. There is a notable UI change: ignored question fragments (data, bind, and control nodes) are now represented by a question-like object in the tree.
Fixes
http://manage.dimagi.com/default.asp?146253 - bind nodes moved to top of form
http://manage.dimagi.com/default.asp?149925 - can't rename questions when ignore/retain is active
http://manage.dimagi.com/default.asp?164398 - case block with nested/ignored update block
cc @wspride

Ignore retain overhaul

---

src/saveToCase.js
src/templates/widget_attachment_case.html
tests/saveToCase.js
tests/static/saveToCase/attachment_property.xml

This adds attachments to save to a case. Follows the pattern set by the other widgets. Could probably be cleaned up, but I think it would be more reasonable to wait until we  do case management in the form builder.
enchantress @czue

Support attachments

---

src/core.js

This is part of a conversion of our analytics tracking from Segment to KISSmetrics. This needs to be released at the same time as the corresponding changes to HQ are changed, which is why I put the don't merge tag on it. @millerdev How does the vellum deploy process work exactly? I've seen the vellum-to-hq script, but I'm not sure when exactly that gets run.

Rename analytics events

---

src/core.js

Bug in https://github.com/dimagi/Vellum/pull/435: new dialog doesn't close when ajax request completes.

close dialog after save completes

---

src/expressionEditor.js

http://manage.dimagi.com/default.asp?170516#955370
Technically it only works in chrome because whenever you do val('blah') to a select it just defaults to the first option.
I think the real bug is here: https://github.com/dimagi/js-xpath/blob/master/models.js#L341 as I don't think == is a valid xpath operator.
This: https://github.com/dimagi/js-xpath/blob/master/models.js#L359 makes me think that whoever wrote this knows that. @czue I think?
Anyways, I tested this in firefox and chrome on linux and it worked on both.
code buddy: @gcapalbo

Convert == to =

---

src/core.js
src/javaRosa.js
src/widgets.js

This cleans up the atwho-containers that will show up at the bottom of the body tag.
A nicer solution would be to PR something to at.js that cleans this stuff up automatically, but I would need to go a little more in depth with the library and how it keeps references (and brush up on coffeescript)
cc: @gcapalbo

Cleanup atwho containers

---

src/copy-paste.js
src/core.js
src/less-style/question-props.less
src/templates/copy_paste_help.html

http://manage.dimagi.com/default.asp?170523
Safari is a real pain when it comes to copy/paste, so I implemented a stupid workaround that should work in any situation where the keydown-copy-paste-event-hidden-textarea dance does not work, which seems potentially useful.
I ran out of energy when it came to implementing the UI. Ideas for improvements are welcome.
Clicking this new button reveals a text box containing the serialized text for the selected questions.
Finally, an *Insert Questions* button at the bottom to deserialize the text and insert questions into the form.

Add alternate copy/paste method for Safari

---

src/less-style/question-props.less

Found this while working on changing to editable divs, but it also applies to master.
Before:
After:
It's probably a small edge case. Could also use word-wrap: break-word on the alert box, but I think that's unnecessary.
code buddy: @gcapalbo

Fix fieldset overflow

---

src/less-style/question-props.less

.atwho-view is styled by at.js css that's included in bower-components, so less just ignores this without the added .atwho-container. Can't do much else since atwho-containers are appended directly to the body (unless there's some magic less thing I couldn't find).

Fix atwho scrolling

---

src/core.js

http://manage.dimagi.com/default.asp?171867
@orangejenny 
https://github.com/dimagi/Vellum/commit/2e0168e13931bc9c34045c59677d26bbbd66f5e4
This was never actually needed but we never noticed because one was jquery ui and overwrite was bootstrap. It gets closed here anyways: https://github.com/dimagi/Vellum/blob/dc0256d6c545fbd902daec4bd725ab6369338982/src/core.js#L1853
cc: @biyeun

Don't close all modals on ajaxstop

---

src/core.js

@orangejenny 
This was the bug Noah ran into:
1. load form
2. make change to form
3. save
4. click lookup table data
5. ajaxstart calls show waiting modal and there's nothing to close it.
I'm reluctant to reintroduce the waiting dialog to datasources since it's going to be refactored heavily soon by @millerdev 
cc: @biyeun

Don't register ajax start

---

src/markdown.js

Haven't been able to replicate this on standalone vellum (I can when loading the form through HQ though) yet, but this protects markdown from non string values. 
I think this was made obvious due to my recent changes in javaRosa to no-placeholder branch
@orangejenny saw that sheel's non working form was missing a translation. I'm going to dig deeper through javarosa to try to fix it there as well, but figured this should be done anyways.
cc: @biyeun

protect against undefined markdown

---

src/javaRosa.js
tests/javaRosa.js
tests/static/javaRosa/non-default-lang-first.xml

The bug:
The non-default language is given in the langs array first
There is no constraint message (or if there is, there is no hint message or help message, etc)
The `constraintMsg` will have an `ItextItem`, but the value will be `undefined`.
If it's the default language it will be set to `nodeID || ""`.
If it's not the default language it will be set to `ItextValue` which is `undefined`
This then trickles down to markdown which expects a string and not undefined.
https://github.com/dimagi/Vellum/blob/bec373a/src/javaRosa.js#L953-L978
In the old javarosa before #458 itext the value was guaranteed to be set to a string. 
cc: @biyeun

Fix no placeholder

---

bower.json

This was tagged since this: https://github.com/vakata/jstree/issues/869
There's no changelog on jstree, so it's hard to see exactly what has changed since that commit. I think it follows major.minor even though there are two numbers https://github.com/vakata/jstree/commit/a0767ceb3fffe1c0b2774d28c811116892a071b8.
I did some quick tests and it still functions as expected

Upgrade jstree

---

src/core.js
src/javaRosa.js
src/logic.js
src/widgets.js
tests/core.js
tests/logic.js

This does a couple of things. 
* generalizes the javarosa widget to a multilline widget
* multiline inherits from normal
* each language has it's own error container
* actually shows the error on label itexts now
Still broken: If you load an itext with <ouput value="."> or a display/calculate condition like `. = 'blah'`. There is no error shown. (It's always been like that)
code buddy: @gcapalbo

Multiline widget

---

src/core.js
src/templates/question_fieldset.html

Two minor tweaks
- scrolling panel too tall in initial load, making it hard to get at the "Advanced link"
- section-level help appearing above section titles instead of in line with them
old
new

style tweaks

---

src/core.js
src/javaRosa.js
tests/core.js
tests/javaRosa.js

@millerdev https://github.com/dimagi/Vellum/pull/485#commitcomment-12074636
I also noticed that these sort of checks should check for the absolute path as well. It's pretty easy to implement, except for itemsets as their `mug.absolutePath` is  `undefined` (It affects them with filters) Am I missing a better way to do that?
code buddy @gcapalbo

Move warnOnCircularReference

---

src/intentManager.js
tests/intentManager.js

Not tested as it relies on the uploader and that's a hole in vellum's tests right now.
Relies on https://github.com/dimagi/commcare-hq/pull/7620 and https://github.com/dimagi/MediaUploader/pull/9
cc: @czue

populate extra fields after html upload

---

src/intentManager.js
src/templates/widget_control_keyvalue.html
src/widgets.js
tests/intentManager.js

@dannyroberts @emord cc @sravfeyn 
Note that this also allows duplicate "extra" keys, and I'm not sure how the mobile app would handle that. But this new feature does not seem worse than what we had before, which was that one of the duplicate key/value pairs was silently discarded.

Allow duplicate intent response keys

---

src/logic.js
tests/logic.js

Not actually used anywhere yet, but pulling this out of my case management work.
Provides a function to only return functions that are not inside of a filtered expression
code buddies: @gcapalbo @kaapstorm

top level path method

---

src/itemset.js
tests/form.js
tests/static/form/instance-reference.xml

http://manage.dimagi.com/default.asp?179723#1000297
This bug only occured in nested filters:
`[count(group_data/data[@key = 'group_type'][. = 'chiefdom']) &gt; 0]`
Also caused a bad UI for the fitler:
@orangejenny 
code buddies: @esoergel @proteusvacuum

Fix regex for complex itemset filters

---

src/core.js
src/mugs.js
src/parser.js
src/templates/question_toolbar.html
src/writer.js

@czue threw this together in a couple minutes. Is this something like you were talking about?
Would need some cleanup/tests. Could also probably throw it in itext just as easily if we wanted it to be able to have different languages (assuming somethign like `value=comment` doesn't mean anything to mobile)

Form comments hacked together

---

src/templates/multimedia_block.html
src/templates/multimedia_modal.html
src/templates/multimedia_queue.html
src/templates/xpath.html

there's no logic to how we use `.btn-inverse`
@nickpell / @emord

standardize buttons

---

bower.json
src/atwho.js
src/less-style/question-props.less
src/main.js
src/templates/atwho_display.html

@dimagi/product I think I recall someone mentioning that seeing the label in the dropdown would be nice. The gray text under the question id is the default lanugage's label. This also allows searching by that label
This PR also introduces some fuzzy searching so that you don't need to type exactly the right text. Notice qustion4 matches question4 in the screenshot. The values are ranked by closeness of text.
Any of this can be pulled into separate PRs.
@millerdev I started to test atwho stuff earlier, but when running the tests, the atwho containers did not clean up quickly enough. (can sync on this separately)

Atwho improvement

---

src/richText.js
tests/richText.js
tests/widgets.js

Prior to this PR multiple contiguous spaces were collapsed into a single space by CKEditor. Additionally, adding multiple contiguous spaces with CKEditor resulted in non-breaking spaces to be encoded in the XForm, which broke expression validation at build/deploy time.
Fixes http://manage.dimagi.com/default.asp?185331
@emord cc @sravfeyn

Preserve contiguous spaces in rich text widget

---

index.html
package.json
tests/main.js

The `--bail` option did not work in v3.5.3. See https://github.com/nathanboktae/mocha-phantomjs/issues/215
Don't forget to run `npm update mocha-phantomjs` after merging this. And you'll need to run that command again when switching to branches made before this is merged.
@emord @orangejenny 
cc @sravfeyn

Upgrade to mocha-phantomjs 4.0.1

---

package.json
src/form.js
src/writer.js
tests/copy-paste.js
tests/form.js
tests/static/form/manual-instance-reference.xml

http://manage.dimagi.com/default.asp?186582#1044106
Original issue: https://github.com/dimagi/Vellum/blob/624473daf7b71ab85058ad0603d346826be00361/src/logic.js#L248-L249
Before it would delete the reference if there was only reference to the instance and then try to re-add it, but this isn't possible with manually written instances to support growth charts and it deleted all the data.
This expands `instanceMetadata.internal` definition to mean "not referenced in the form"
@millerdev 
cc: @gcapalbo

Don't delete instances on dereference

---

src/richText.js

This happens before the close button is added. Right now there's dead space between drag container and close button
@millerdev 

No close button adjustment for drag container

---

lib/SaveButton.js
src/core.js

@orangejenny @millerdev @emord cc: @gcapalbo 
This modifies the save button to add CSRF header to its post request if one exists. As soon as CSRF protection on hq goes live, it wont be possible to save forms in the formbuilder without this. The token will be passed in through the options object.
If there is not a csrf token passed to the save button, no behavior will change.
Merging is not urgent because it will be a bit before the CSRF protection is up but I do not see a downside to merging early.

adding csrf token to save button

---

src/core.js
src/expressionEditor.js
src/javaRosa.js
src/logic.js
src/main.js
src/parser.js
src/richText.js
src/xpath.js

encapsulate xpath into it's own file so we can be sure that vellum uses the same xpath parser throughout. uses new js-xpath
Doesn't really make a difference at the moment, but pulling it out from my current dev branch
cc: @esoergel

Encapsulate xpath library

---

src/atwho.js
src/core.js
src/expressionEditor.js
src/itemset.js
src/parser.js
src/uploader.js
src/writer.js
tests/atwho.js
tests/options.js
tests/utils.js

Turns out cool features slow down tests
Before: `./test  103.82s user 1.18s system 96% cpu 1:48.64 total`
After: `./test  60.94s user 1.32s system 95% cpu 1:05.35 total`
Removes atwho from vellum tests. Atwho is currently tested by creating it's own input and has a mock form.
Depends on https://github.com/dimagi/commcare-hq/pull/9859
@millerdev 
cc: @sravfeyn

Speed up tests

---

src/templates/multimedia_modal.html

Necessary because of https://github.com/dimagi/MediaUploader/pull/11
@emord this needs to go into today's deploy
cc @sravfeyn

Add B3 selector to multimedia modal

---

src/less-style/structure.less

In Chrome on OSX, the case properties panel's scroll bar is visible on top of the XML source modal.
http://stackoverflow.com/questions/16874546/strange-z-index-behavior-with-scrollbars-under-chrome
@emord

Witchcraft

---

bower.json
build.js
tests/form.js
tests/main.js

@millerdev @orangejenny 
Right now vellum is overridding HQ's underscore (1.6.0) with our own packged one (1.4.4) changes here (look at 1.5.0 through 1.6.0): http://underscorejs.org/#1.6.0
This upgrades underscore and stops it from being packaged in local-deps
As far as I know there's no bugs that this causes yet.

Upgrade underscore

---

src/widgets.js
tests/formdesigner.lock.js

@emord 
before
after
Switched to icon because "Edit" padding changed & "Edit" no longer fits cleanly (on my screen, which isn't all that small).

Fix button alignment in lookup table data

---

src/atwho.js
src/core.js
src/form.js
src/fuse.js
src/tsv.js
src/util.js
tests/atwho.js
tests/static/atwho/test1.xml
tests/tsv.js
tests/utils.js

A refactor of how we do fuzzy finding.
Instead of caching in src/atwho.js. this moves fuse (fuzzy search library) to the form. This means that we no longer need to go through all mugs everytime an autocomplete is created, and in the future for #case references if datasources load while you are already autocompleting new references should pop up seamlessly
cc: @calellowitz

Move fuse to form

---

src/javaRosa.js

http://manage.dimagi.com/default.asp?221799
Tried writing a test for this, but the backspace isn't working in phantomjs 
```
it("delete text before output ref", function () {
util.loadXML("");
var mug = util.addQuestion("Text", "question1");
var target = $("[name=itext-en-label]");
target.val('question1<output value="/data/question2" />').change();
vellum_util.setCaretPosition(target[0], 2, 9);
target.trigger({
type: "keydown",
which: 8,
ctrlKey: false
});
target.change();
var val = mug.p.labelItext.get('default', 'en');
assert.equal(val, '<output value="/data/question2" />');
});
```
The value stays `question1<output value="/data/question2" />'`. I did verify that does work in chrome though.
cc: @dannyroberts

weird backspace behavior

---

src/richText.js

http://manage.dimagi.com/default.asp?222370
Tried making a test using the ckeditor's focusManager, but wasn't able to get it to blur, and display the placeholder. This bug shows up due to a conflict between bubbles and another plugin we use
cc: @dannyroberts

remove placeholder on focus

---

src/javaRosa.js
src/uploader.js
tests/javaRosa.js
tests/questionTypes.js
tests/static/all_question_types.xml
tests/static/javaRosa/test-xml-2-with-bind-constraint.xml
tests/static/javaRosa/test-xml-2-with-only-bind-constraint.xml
tests/static/javaRosa/test-xml-2.xml

http://manage.dimagi.com/default.asp?223608#1126669
It's a little weird that we use the itext type when displaying the types of media. never noticed until now. It'll take a bit of a refactor of how we use `SUPPORTED_MEDIA_TYPES` so it may be out of scope for this
@ctsims

Inline video

---

src/expressionEditor.js
src/templates/xpath_validation_errors.html

Noticed this while in Moz. The old error wasn't useful at all, because the error message is already formatted. not sure when it was possible to have multiple error messages
Old:
New:
buddy: @proteusvacuum

Use <pre> for error message

---

src/richText.js
tests/richText.js

It's backwards-compatible, and someday we'll upgrade to 1.8
@emord

Make _.template calls 1.8-compatible

---

src/richText.js

@emord 
When bubbles get created, executing `createPopover` has been stealing focus.

Stop focus from jumping to different language's textarea

---

src/atwho.js

CKEditor sometimes inserts zero-width spaces into the editor, which is "not a bug" (https://dev.ckeditor.com/ticket/10031) but does interfere with our ability to decide whether or not a given string matches the pattern that should cause atwho to pop up.
This has been manifesting as the following bug:
- Type a valid hashtag like `#case/child/dob`
- Type `[space]`, which turns the path into a bubble (as of https://github.com/dimagi/Vellum/pull/671)
- Type `#` which should pop up atwho, but doesn't, because ckeditor inserted some zws characters after the bubble.
@emord

Watch for zero-width spaces when matching for atwho

---

src/richText.js

@emord 
Seems that widgets get checked (and therefore destroyed) on `afterInsertHtml` but not on content change. Slightly concerned about performance, but the `key` event is less reliable than `change`.
should fix http://manage.dimagi.com/default.asp?220534

More robustly destroy bubble popovers

---

src/core.js

@orangejenny from field/dev
> [10:56:11 AM] Jennifer Harlow: Oh, but "Use Raw References" was already checked.  But there were bubbles
buddy @NoahCarnahan

Fix easy ref wording

---

src/richText.js
tests/richText.js

http://manage.dimagi.com/default.asp?232527
@millerdev 
We use the undo plugin to gain access to a change event. If `canUndo !== false` then `execCommand` will send a change event which enables the save button

creating popovers is not undoable

---

src/mugs.js
tests/questionTypes.js
tests/static/questionTypes/select1-help-with-type.xml

http://manage.dimagi.com/default.asp?231052#1198906
Vellum has never looked at types in binds to determine select vs select1, so this is only an issue for forms imported elsewhere. Mobile uses the type over the tag in the control tree
cc @czue

Don't write type to select questions

---

src/saveToCase.js
tests/saveToCase.js

This was tracking the same setvalue in two different places. once in the form, the other in the mug. this removes it from the form once it is tracked in the mug.
@czue

Fix save to case case id setvalue

---

src/logic.js
tests/logic.js

http://manage.dimagi.com/default.asp?234197
The logic manager did not remove references contained in itext labels when the question was deleted.
cc @snopoke

Remove references in labels when deleting a question

---

src/richText.js
tests/databrowser.js
tests/richText.js

Second attempt at http://manage.dimagi.com/default.asp?232759 (first #695)
There are still strange editing behaviors related to whitespace after widgets (bubbles) in CKEditor. The most annoying to me is on backspace or left-arrow to remove or move within spaces following a bubble (sometimes the widget is selected instead of the conventional action of deleting or moving past the space before the cursor). Also selecting a different mug and then returning causes the ZWS chars to be removed or converted to regular spaces, which can cause a mildly inconsistent editing experience.
@emord

Fix cursor hiding after insert expression bubble

---

src/saveToCase.js
tests/saveToCase.js
tests/static/saveToCase/create_2_property.xml

http://manage.dimagi.com/default.asp?234647#1200207
This wouldn't correctly load the case id if multiple save to case questions were using the the same value for the case_id. Example: create two cases in a form and use 'uuid()' to give them id, only one of them in vellum would have kept the value
@millerdev @snopoke

Fix loading case ids with same string

---

src/javaRosa/itext.js
src/javaRosa/plugin.js

Followup for https://github.com/dimagi/Vellum/pull/703 : building an app requires that choices have labels, but their "labels" might be images, etc., not text.
@emord 
cc @biyeun

Allow multimedia to fulfill itext requirement

---

src/escapedHashtags.js
tests/escapedHashtags.js

http://manage.dimagi.com/default.asp?234894#1200992
The bug was due to having an invalid xpath ``` `#hashtag1``#hashtag2` ```. Hashtags shouldn't have ` in them anyways, so dropping support for that in the form builder
@orangejenny @snopoke

Don't support delimiters within hashtags

---

src/intentManager.js
tests/intentManager.js

This was for the original spec of the printing widget. It was removed due to a bug in the uploader and then we switched to binary zebra print templates. I don't think it will ever be used again
@snopoke

Remove parse fields

---

src/atwho.js
tests/atwho.js

Only adds autocomplete to inputs when input is focused.
With easy references there is a dom leak for atwho. hint/validation/help/something itext's are hidden by default. ckeditor initializes these with `contenteditable=false` (known: https://github.com/dimagi/Vellum/blob/f6cbe1ff9ff40dcc330fa0705a7a040f569463ae/src/richText.js#L234-L235) this means that atwho was initializing, but never destroying those elements or the references they held unless each input was focused everytime a user changed a question.
@orangejenny @snopoke

fix dom leak

---

src/escapedHashtags.js
src/form.js
src/xpath.js
tests/escapedHashtags.js
tests/logic.js

http://manage.dimagi.com/default.asp?235588
introduced in https://github.com/dimagi/Vellum/pull/720/commits/52436344d4d1fd4effc0e6139c2993b9bce22f9e
hashtagDictionary changes addresses, so when the form's
hashtagdictionary changes, the parser's does not
cc @snopoke

parser references form instead of dictionary

---

bower.json
tests/richText.js

@emord The `should destroy popover after destroy` test is the one that's problematic. It's fine in the browser, but when run in the console, it seems to cause later tests to fail. Reordering it to be the last test in its `describe` block makes all tests pass. Which doesn't feel great, but I'm not enthused about spending more time on figuring out what's going wrong.

Bootstrap 3.3.7

---

src/core.js

http://manage.dimagi.com/default.asp?236076#1209421
This already checks if help exists, so we don't need a default object
https://github.com/dimagi/Vellum/blob/master/src/templates/question_fieldset.html#L8
@phillipm 
buddy @czue

don't show help bubble

---

src/richText.js
src/widgets.js
tests/richText.js

@orangejenny I wasn't able to get the `lang` attribute to provide input language specific spellchecking. It's possible I misunderstood whatever blog post I saw.
buddy @czue

Don't use spellchecking on xpaths

---

src/atwho.js

http://manage.dimagi.com/default.asp?235907
Verified that this behaves reasonably if you type something like `/data/data/question` (where `/data/` is the at string).
@emord

Don't require space before matching atwho

---

src/richText.js
tests/richText.js

This erroneously bubbled things like `<output value="#form/today - now()" />` because it started with a form ref
buddy @czue

Don't bubble if expression has more than a reference

---

src/window.js

Shot in the dark at http://manage.dimagi.com/default.asp?234272 ...wondering if the issue is that the onready handler that calls `adjustToWindow` isn't reliable. See https://jquery.com/upgrade-guide/3.0/#breaking-change-on-quot-ready-quot-fn-removed
@emord

Don't use ready 'event'

---

src/commtrack.js

Apparently commtrack icons have never shown up in HQ. Sorry @esoergel 

Fix commtrack icons

---

src/core.js
src/dataSourceWidgets.js
src/databrowser.js
src/datasources.js
src/form.js
src/fuse.js
src/itemset.js
src/javaRosa/itextWidget.js
src/parser.js
src/util.js
src/widgets.js
src/writer.js
tests/atwho.js
tests/databrowser.js
tests/datasources.js
tests/itemset.js
tests/javaRosa.js
tests/options.js
tests/static/datasources/case-property.xml

http://manage.dimagi.com/default.asp?237032
This bug was really hard to figure out and fix because of a timing issue between loading of the data browser and data sources. This is a major refactor of how the form object gets a list of valid hashtags from data sources. Hashtags and hashtag transformations are now available immediately when data sources are loaded rather than after the data browser is initialized. The data browser now does only one thing: display a tree of case properties, and it no longer mutates the form during its initialization phase.
A few other cleanup items were done to make it easier to think about the state of vellum in tests:
- data sources state is now local to a vellum instance rather than global
- the data browser no longer has global state.
Probably easiest to …

Fix datasources state

---

src/core.js
src/javaRosa/itextBlock.js

jQuery 3 migration plugin has been complaining about this.
> As of jQuery 1.6, the .attr() method returns undefined for attributes that have not been set. To retrieve and change DOM properties such as the checked, selected, or disabled state of form elements, use the .prop() method.
(http://api.jquery.com/attr/)
@biyeun / @emord

prop not attr for DOM properties

---

src/form.js
tests/undomanager.js

This fixes half of http://manage.dimagi.com/default.asp?238232, and will probably solve most of the cases of this bug popping up again.
At the moment, it's a little unclear to me how best to have the undo manager check the node id for conflicting nodes. Right now that code is in `moveMug` and undo uses `insertMug` to insert. I want to think a little harder before moving/duplicating that code into `insertMug` or changing the way the undo puts mugs into its queue
@millerdev @orangejenny buddy @czue

hide undo after adding a question

---

src/core.js

http://manage.dimagi.com/default.asp?238845
Closing one modal and then immediately opening another one doesn't play nicely with the fade transition. This looks like an issue with bootstrap, but an easy one to work around by turning off the transition in the case where we're closing a modal because we're about to open another one.
@millerdev

Multiple modals

---

src/core.js

`$(data.data.obj).vellum("get")` and `$(data.data.obj.context).vellum("get")` both return the vellum object, and `.context` is deprecated in jQuery 3.0.
https://jquery.com/upgrade-guide/3.0/#breaking-change-deprecated-context-and-selector-properties-removed

Make drag & drop work in jQuery 3

---

src/core.js
src/templates/main.html

Don't think this is important enough to be always visible, and user testing has pushed me to want to reduce clutter in vellum. @dimagi/product feel free to register an objection.
before
after

Move full screen button into tools menu

---

src/core.js
src/datasources.js
src/escapedHashtags.js
src/form.js
src/logic.js
src/parser.js
src/richText.js
src/util.js
src/widgets.js
src/xpath.js
tests/copy-paste.js
tests/core.js
tests/databrowser.js
tests/diffDataParent.js
tests/escapedHashtags.js
tests/form.js
tests/logic.js
tests/modeliteration.js
tests/parser.js
tests/richText.js
tests/static/all_question_types.tsv
tests/widgets.js
tests/writer.js

http://manage.dimagi.com/default.asp?237816
Includes a major refactor of escaped hashtags: they're now only used inside the rich text widget and when writing invalid expressions in XML. Best to review commits individually 🐠 the commit messages are descriptive.
@emord

Fix copy bubble from label to expression input

---

src/core.js
tests/utils.js

In question properties, collapse all sections by default except for Basic. Then, whenever someone collapses or expands a section, remember that decision and respect it in the future.
Quick and dirty and testless, since the failure mode of this is not a big deal.

Make collapsing decisions sticky

---

src/core.js
src/expressionEditor.js
src/form.js
src/javaRosa/itextWidget.js
src/javaRosa/util.js
src/mugs.js
src/parser.js
src/widgets.js
src/writer.js
tests/escapedHashtags.js
tests/form.js
tests/logic.js
tests/static/form/name-template.xml
tests/static/writer/ignore-richtext-and-markdown.xml
tests/writer.js

This is mostly refactoring and a few new tests and minor bug fixes. Makes it easier for me to reason about where rich text gets enabled/disabled. The biggest change is that vellum now ignores `vellum:attr="..."` attributes when rich text is disabled. 
Review commits individually 🐠 the messages are descriptive.

Clean up rich text flags

---

bower.json

keeping it up to date
markdown-it has a new version out as well, but I'm not confident in one of the changes in 8.0.0. Need to test it out to see the differences in form builder before upgrading it
@esoergel

jstree 3.3.3

---

src/templates/xpath.html
src/widgets.js

@emord 
I'd expected to do this by tweaking a template, and then learned that the expression editor has a generic outer template, and making it question-specific looked like a bear.

Contextual title for expression editor

---

src/logic.js
tests/itemset.js

http://manage.dimagi.com/default.asp?241382
The nodes in the tree and question nodes in xml are not 1:1, so if that's the case use the parent path. I think we've done this before, but I can't remember/find where it's been done before, seems like something that could be pushed to the mug if it gets done a lot though

Use parent path if current path isn't real

---

src/core.js
src/mugs.js

@emord 
Left the label help at the section level, rather than have it repeated for every language.

Associate question ID help with question ID instead of section

---

src/logic.js
tests/logic.js
tests/static/logic/test-xml-1.xml

Right now all case references are stored under `#case/` in `this.reverse`. the full path is stored inside the reference but it will take a slightly larger refactor to get that to work.
Probably not obvious but it's tested as there are functions later that test that it is not returned by `findUsages`
@dannyroberts @proteusvacuum

Don't error for #case refs

---

src/less-style/inputs.less

Took a long time to track this down. `pre-wrap` caused a string of normal spaces (char 32), rather than alternating space/`$nbsp;`, to be entered (at least in Chrome), which was a problem because normal spaces are skipped by CKEditor when navigating toward a widget with arrow keys or backspace/del.
This fix was tested in Firefox and Chrome.
@emord

Fix CKEditor skipping many spaces

---

src/core.js
src/intentManager.js
src/javaRosa/itextWidget.js
src/uploader.js
src/widgets.js
tests/intentManager.js
tests/javaRosa.js
tests/utils.js

Fixes:
- http://manage.dimagi.com/default.asp?229441
- http://manage.dimagi.com/default.asp?220337
This implements most of the items in the [proposed solution](http://manage.dimagi.com/default.asp?229441#BugEvent.1172875). Things not implemented:
- Itext MM paths are still assigned prior to upload, although the path changes each time a new file is uploaded.
- The button for uploading new MM content still changes its title as it did before.
- The new *Replace ... for all linked questions* button is not implemented.
Once this is merged each multimedia upload done in the form builder will create a unique new `jr://commcare/...` path, which means that the media map for a given app could grow to be larger than it would have previously if many media items are uploaded and then re-uploaded …

Fix print question type template collision

---

src/atwho.js
src/core.js
src/databrowser.js
src/datasources.js
src/form.js
src/javaRosa/plugin.js
src/logic.js
src/richText.js
src/templates/external_sources_tree.html
src/util.js
src/xpath.js
tests/databrowser.js
tests/datasources.js
tests/escapedHashtags.js
tests/form.js
tests/logic.js
tests/options.js

Add support for new data sources schema elements that allow user properties to be specified and referenced with hashtag expressions (`#user/property`). It also removes magic/ambiguity from the data sources schema. Finally, all hard-coded references to `#case` hashtags have been removed since the data sources schema may define arbitrary hashtag names.
All changes here should be entirely backward-compatible with the existing data sources schema provided by HQ. Until HQ is updated to provide a new schema containing user properties, the only end-user visible change is c51fd69.
Spec: https://docs.google.com/document/d/1kPVwZketyWl6aRo1ZNCM3EngkrTsgmFbnBXAv-FThKU
Review commits individually 🐠 

User properties

---

src/dataSourceWidgets.js

http://manage.dimagi.com/default.asp?243450
Not particularly proud of this one. There are no tests because the data source widgets don't have tests. Also, they haven't been updated to support rich text. Hashtags do work, but no bubbles (obviously) and no auto-complete.
@emord

Fix drag/drop in data source widgets

---

src/form.js
tests/core.js
tests/richText.js

This fix was hard to figure out and I'm not proud of it, but it works so I'm going with it. The event dependencies are messy. Mug `property-changed` [appears to be sort of deprecated](https://github.com/dimagi/Vellum/blob/6516916bfcb99a2783f264fc931398a1b5a887ec/src/form.js#L890-L892), but I couldn't think of a better way to implement it without a massive refactor and I'm not sure what Mike White had in mind by "some sort of data binding."
The first commit is an unrelated debugging annoyance fix.
http://manage.dimagi.com/default.asp?243656

Fix name in tree after change choice node ID 

---

src/core.js

Noticed this while looking at removing the "New Form" content for onboarding.
Before, empty forms display with the "Question Details" header and a horizontal line:
After, those elements are gone:
A little nervous about removing this, but tests pass and I verified that both empty and non-empty forms load as expected (non-empty forms select the first question and display its question properties).
@millerdev / @emord

Don't display right-hand content when there aren't any questions

---

src/core.js

http://manage.dimagi.com/default.asp?244447
This is a timing issue. When you drag a bubble over an input in question properties, jstree doesn't recognize it as a legal place to drop (I think because you're not in the tree...didn't delve deeply into the jstree logic) and [shows the red X](https://github.com/vakata/jstree/blob/master/dist/jstree.js#L6709). But vellum does recognize that this is a legal place to drop and [shows the green checkmark](https://github.com/dimagi/Vellum/blob/master/src/core.js#L1006).
Both of these pieces of code are inside `dnd_move` handlers, and whichever one runs last effectively "wins." Event handlers are run in the order they're registered, which in this case isn't reliable: the jstree handler is attached on document ready, the vellum handler on vellum …

Wait to attach drag events until first drag

---

src/saveToCase.js

I don't think I've ever used any other value for this.
note that `/data/meta/userID` would be another equivalent option if we prefer that. this has the benefit of working with nonstandard `meta` blocks though that's not really a thing that we care about.

default user_id to value from session

---

src/core.js

@orangejenny @millerdev This came from field dev/stack exchange post. We shouldn't have this box because it isn't reflected in HQ, but it would change it on mobile leading to very confusing behavior. Changing on the form page in HQ should be the only way to change this
@benrudolph @gcapalbo

don't let people change the form name

---

src/databrowser.js

@emord @millerdev @orangejenny cc: @czue 
this adds popovers to the data browser, the are correctly rendered after searches or opening of the tree. tested with 300+ case properties for load issues and there didnt seem to be a problem. When there is no description, there is no popover not an empty one

adding popovers with descriptions to databrowser

---

src/uploader.js

https://manage.dimagi.com/default.asp?248873 voodoo magic
Since #810, the Print question type does not initialize its template path until a template is uploaded. I couldn't find any changes since then that would have caused this bug, but I can also hardly imagine that we did not test this workflow before releasing that change (it passed QA).
Since the template path is initially blank, the [`mediaUploadComplete` handler](https://github.com/dimagi/Vellum/blob/03750224202048d01e682c3028e139a484ea3f2d/src/uploader.js#L206-L207) was not called because the [selector (constructed with said blank path) used to trigger the event](https://github.com/dimagi/MediaUploader/blob/d8e910547683e63a38fdf82e3195be0a2b83edc0/hqmedia.upload_controller.js#L551) matched nothing. This change ensures that the …

Tiptoeing around media uploader minefield

---

src/less-style/dropdown.less

The submenu arrows on prod are currently invisible:
Whereas they should look like:
Looks like an issue with the minifier, where `border-left-color: #ccc;` wasn't included in the minified file. Fixed by combining `border-color` and `border-left-color` into one rule.
cc @dannyroberts

v2: Make submenu arrows not invisible

---

src/core.js

@millerdev / @emord 
Used `Expand Editor` / `Shrink Editor` because leaving it as `Enter Full Screen` plus the shortcut code broke onto two lines.
cc @dannyroberts

Keyboard shortcut for full screen

---

src/core.js
src/less-style/question-props.less
src/mugs.js
src/widgets.js

As discussed in #vellum chat. I feel a little weird about not having the id visible for new users, but I think that's just resistance to change. Guessing that a heavy majority of users will have logic open most of the time, and that this'll just get the id out of the way for brand new people until they get more comfortable in the form builder.
fyi @biyeun

Move question id into logic

---

src/jstree-plugins.js

F2 to edit node name was referenced in https://manage.dimagi.com/default.asp?249819 I didn't even know about this feature, but it does nothing so just disabling it.
@emord @benrudolph

Disable F2 to rename tree node

---

src/core.js

Experimenting with this for the next few user tests.
My hope is that now that the id's placeholder updates itself as you type into the label, the id will look "filled out" and people won't be so compelled to type in it.
@millerdev / @biyeun / @emord

Move question id back into basic

---

bower.json

@orangejenny I think the only things that use the deprecated functions are at.js and jstree
https://blog.jquery.com/2017/03/16/jquery-3-2-0-is-out/
> This release includes some bug fixes, improvements, and some deprecations. There should be no compatibility issues if upgrading from jQuery 3.0+.

jquery 3.2.1

---

src/core.js

Reason for doing this is that using `createQuestion` means that when a choice is added, the parent select question ends up selected. This change makes it so that the new choice question ends up selected.
@millerdev / @emord 
cc @NoahCarnahan

Add choice with addQuestion, not form.createQuestion

---

src/richText.js

https://manage.dimagi.com/default.asp?250396
Not proud of this. The extra line is caused by [this code](https://github.com/dimagi/Vellum/blob/master/src/richText.js#L263-L268) which is needed for atwho/bubbles to insert correctly.
@emord 
cc @esoergel

Blank placeholder to appease ckeditor/firefox

---

src/form.js
tests/questionTypes.js

Deal with some issues Derek raised about the workflow of adding choices to a select question.
Previously, when you added a choice, the label and id would default to `choiceN`, which the user would inevitably need to overwrite. Now I'm letting the id and label default to blank, which is a better workflow, but because this causes a validation error, I'm letting the validation run, assuming it's going to error on `nodeID` and the label, and then removing those errors, which is a bit sketchy.
@emord 
cc @esoergel

Allow choices to start off without label or id

---

tests/questionTypes.js

https://github.com/dimagi/Vellum/pull/887#pullrequestreview-35520379
I haven't actually been able to reproduce the bug in a test, even when adding choices repeatedly. Did notice that tests don't need to call `ensureCurrentMugIsSaved` anymore, though.
@millerdev

Update add_choice tests

---

bower.json
tests/logic.js
tests/saveToCase.js

`assert.sameMembers(["#form/text2","#form/text1","#form/text2"], ["#form/text1","#form/text2"])`
-  Before (chai 3.5.0) -> pass
- After (chai 4.0.1)  -> fail
- Replace with `assert.includeMembers`
`assert.include([{a: 1}], {a: 1})`
- Before (chai 3.5.0) -> pass
- After (chai 4.0.1)  -> fail
- Replace with `assert.deepInclude` (new in Chai 4)

Fix errors related to chai upgrade

---

src/fuse.js
tests/form.js
tests/main.js

Earlier today while editing a form loaded with easy references disabled I noticed that I could not auto-complete case references after turning on easy references.

Reload fuse data on enable easy references

---

src/itemset.js
tests/itemset.js
tests/options.js

This is necessary because sorted itemsets are only supported on mobile 2.37+. HQ PR to follow.
Also fixed a bug when pasting sorted itemsets.

Sorted itemsets feature flag

---

src/window.js

https://manage.dimagi.com/default.asp?258554
This has existed for a while, just wasn't noticeable until app preview styles started depending on `.full-screen`.

Fix question properties not resizing properly

---

src/commander.js
tests/commander.js

Bug discovered by @nsclark 
also
- "Multiple Choice Lookup Table" before "Multiple Choice"
- "Checkbox Lookup Table" before "Checkbox"
This issue prevented add question position autocomplete from working for certain question types.

Commander: match "Date and Time" before "Date"

---

src/core.js
src/less-style/structure.less
src/templates/alert_global.html
src/templates/main.html
tests/utils.js

https://manage.dimagi.com/default.asp?260647
Originally did this as discussed on slack, with messages showing next to the save button, then remembered that we already have an area for messages.
On additional messages, the message bar will quickly fade out and then fade back in, to stick to vellum's "one message at a time" stance while still catching the user's eye if an additional person has opened the form.
@emord / @millerdev 
cc @nickpell

Expose messages publicly

---

src/core.js
tests/core.js
tests/options.js

https://manage.dimagi.com/default.asp?266075
This fixes the issue where the save button is disabled after canceled overwrite warning. I am unable to reproduce (or even understand how it would happen) the second part where the person with a conflicted form overwrites the other users work without a warning.
🐠 Review by commit

Fix saved after overwrite warning

---

package-lock.json
src/commtrack.js
tests/commtrack.js
tests/static/commtrack/balance-block-setvalues.xml
tests/static/commtrack/balance-block.xml
tests/static/commtrack/transfer-block-setvalues.xml
tests/static/commtrack/transfer-block.xml

https://manage.dimagi.com/default.asp?267194
Ignore the first commit, which just adds [package-lock.json](https://docs.npmjs.com/files/package-lock.json)
Best to review the other two commits individually 🐠 

CommTrack module: setvalue -> bind 

---

src/core.js
tests/core.js
tests/utils.js

https://manage.dimagi.com/default.asp?266075
Do not overwrite conflicting form on switching from patch to full form save. The switch from patch to full save happens if the patch content is bigger than the new form being saved.
This change will have no effect until https://github.com/dimagi/commcare-hq/pull/19586 is also deployed.
@emord @orangejenny cc @snopoke @esoergel

Fix overwrite conflicting form without prompt

---

src/util.js

Tested on Chrome and Firefox on Mac. Would be nice if someone tested them on Windows and Linux.
@orangejenny @emord cc @gcapalbo

Fix hotkeys on Firefox (at least on Mac)

---

src/core.js
src/javaRosa/itextBlock.js
src/javaRosa/plugin.js
tests/javaRosa.js

ICDS is considering stretching to 15+ languages and have run some tests for a bottleneck with form builder not able to support that many lanugages. While we are working on other possibilities, i believe the blocker is heavy HTML and this would help tackle that.
I did some test and this change should do the following:
render display text in form view for the current language and the default language. The reason for keeping both of them and not just the current language/default language is to avoid some issue i saw when adding questions with just current language display text available. But if default langugage is the current lang, it will just show one language.
One can still do translations by switching to the other language but i don't think the app builders use that in ICDS. …

Mk icds app trans hq 2

---

src/javaRosa/itextBlock.js
tests/javaRosa.js

introduced in #941.
When Question ID is used for display instead of one of the available languages a text box with label `Display Text (_ids)` is added.
This PR adds a check to ensure that display language is one of the app languages.

Mk fix id display

---

tests/javaRosa.js

These tests appear to have been constructed incorrectly from the very beginning (they should have been async but were not). Also, Question ID is not copied into itext labels anymore.
@mkangia @orangejenny

Question ID is not copied to label since long ago

---

src/databrowser.js

https://manage.dimagi.com/default.asp?272806
Looked into doing more clever behavior specific to the error code but found that unreliable - redirects (can show up if you get logged out) show up as 200s, and faking an error [like this](https://github.com/dimagi/commcare-hq/blob/master/corehq/apps/domain/views.py#L2861-L2863) with an explicit status code just came through as a 500. So I went the route of just putting up a vague error.
@millerdev / @emord

Show error message when app properties fail

---

src/mugs.js
src/parser.js
tests/form.js

Product Note: When a user updates the question ID in formbuilder, remind them that previously submitted data is unaffected.
https://trello.com/c/peoYQUMn/77-crs-items-for-q4

inform user changing a saved question ID that old data is unaffected

---

src/core.js
src/form.js
src/mugs.js
src/util.js
src/widgets.js
tests/form.js

https://trello.com/c/peoYQUMn/77-crs-items-for-q4-alert-ux-changes
This implements the following changes:
1) Don't re-open closed question ID warning after navigating to a different question. https://github.com/dimagi/Vellum/commit/6f515fa28c0ad6619e019cab15db3bb875762cc3
2) Remove all existing warnings after saving a form. https://github.com/dimagi/Vellum/commit/348f4d0cda763e20a14ce1fd4ec2c659794f3491
3) Only show warning after at least one form has been submitted. https://github.com/dimagi/Vellum/commit/822242722df4638f61cccf2a9a6645128724af74
4) Updates warning text. https://github.com/dimagi/Vellum/commit/b17352633dc467e2c817dedc2011377e41880269
🐡

"Question ID changed" warning updates

---

src/mugs.js

https://dimagi-dev.atlassian.net/browse/HI-789
Strictly speaking this isn't necessary for vellum, it's an HQ bug...but this is a much easier fix. I'm guessing "case" is also illegal for HQ-based reasons.
The problem is that vellum's options include the form XML itself, which includes the string `<script>`, and those options are encoded as JSON for initial page data, we interpret that as an attempted script injection and [change it](https://github.com/dimagi/commcare-hq/blob/df912c4fa1179a79a76543269c358d7477119270/corehq/apps/hqwebapp/templatetags/hq_shared_tags.py#L54) in a way that jQuery can no longer decode it as JSON.

Added 'script' to disallowed question IDs

---

src/copy-paste.js
src/form.js
src/itemset.js
src/javaRosa/plugin.js
src/modeliteration.js
src/mugs.js
src/richText.js
tests/copy-paste.js
tests/datasources.js

This fixes an unintuitive behavior when copying/pasting multiple questions that contain references to each other. I've wanted to fix this ever since [Jessica Long reported it almost two years ago](http://manage.dimagi.com/default.asp?265411), and finally decided to do it today.
🐡 Review by commit.
@dimagi/product this makes a subtle change in behavior, and I think it's more intuitive and therefore better than the previous behavior. We should announce it. Do we need to do anything else?

Maintain xpath referencess on copy/paste

---

src/less-style/structure.less
src/templates/main.html
src/window.js

https://dimagi-dev.atlassian.net/browse/HI-813
Most of the changes are `height` => `max-height` so that scrolling content isn't forced to be as tall as the window.
Tested out on a form with a lot of languages and a form with a few languages. Tested out full screen mode.

Updated languages menu to scroll vertically

---

src/core.js

Noticed while working on https://github.com/dimagi/commcare-hq/pull/25531
The code is checking for an "Invalid XML" prefix but the message starts with "Error: Invalid XML" instead.
before
after

Updated invalid XML error to be friendlier

---

src/xml.js
tests/xml.js

https://dimagi-dev.atlassian.net/browse/SAAS-11032
fixes an issue where if an ampersand and an output ref are present in an itext block, the text following the output ref gets truncated due to a strange behavior that this triggers in jquery's `parseXML`

fix truncated text issue with output refs

---

src/javaRosa/util.js

While adding support for markdown tables on HQ, we missed out this format which is not picked up by the regex we wrote. 
```
| Column1      | Column2 |
| ----------- | ----------- |
| 100      | 200     |
| 110   | 215        |
``` 
For more details see this comment https://github.com/dimagi/Vellum/pull/977#discussion_r494952540
https://regex101.com/r/2QZeLp/1
```
| col1    | col2    | col3 |
|:----:|:----:|:----:|
| r1c1 | r1c2 | r1c3 |
| r2c1 | r2c2 | r2c3 |
```
https://regex101.com/r/5mWDhq/1
```
| col1    | col2    | col3 |
|----|----|----|
| r1c1 | r1c2 | r1c3 |
| r2c1 | r2c2 | r2c3 |
```
https://regex101.com/r/Jbqsx3/1
```
| Column1      | Column2 |
| ----------- | ----------- |
| 100      | 200     |
| 110   | 215        |
```

updated regex to support different markdown table format

---

index.html
src/core.js
src/javaRosa/plugin.js
src/templates/main.html
tests/bulkActions.js
tests/main.js
tests/options.js

https://dimagi-dev.atlassian.net/browse/SAAS-11387
Adds one option in registration/survey forms to mark all questions required:
adds an additional option in followup forms (or forms where the datasource panel is visible) to set default values of all matching properties to the existing matching case value:
confirmation dialog for marking all questions as required:
confirmation dialog for setting default values:
Definitely pushing this through QA.

Implement ability to make all questions: 1. load case properties as default values 2. required

---

.github/PULL_REQUEST_TEMPLATE.md
.github/dependabot.yml
.github/labels.yml

this adds config files for labels, dependabot, and PR templates to vellum to be more in line with hq's config

Add some helpful github tools (labels, dependabot, PR templates) to vellum

---

src/core.js
src/widgets.js
tests/urlHash.js

Ticket Link - https://dimagi-dev.atlassian.net/browse/SAAS-11597
Whenever the page was getting loaded for the first time `window.replaceState` was getting called for every question in the form. This was causing a Security Error dialogue box to appear in Firefox.
The fix that we made calls the browser API only when it is required i.e whenever question_id is modified or changes in the forms are saved.

Fix - "Security Error" Dialogue Box in Firefox

---

.travis.yml
Makefile
README.md
package.json
src/main.js
src/widgets.js
start-server.sh
test
tests/urlHash.js
yarn.lock

Upgrade less to 3.10.3, the same as HQ
Ran tests locally, both headless and in browser.
:tropical_fish: Review by commit. Some of the earlier commits are cleanup for the fact that jshint was removed from travis runs a while ago. I also run the test server on a different port, so parameterized that as well.

Upgrade less

---

src/javaRosa/plugin.js
tests/javaRosa.js
tests/static/javaRosa/single-lang-second-select-with-help.xml

When a new language has been added to the form, markdown itext for questions that are not selected during a form edit session may not be not initialized. This caused an error on write XML (save). Note that the first question is usually selected on initial form load, so this bug did not occur on forms having a single question.
```
TypeError: Cannot read property 'replace' of undefined
at fixEmptyTags (src/xml.js:167:26)
at Object.query (src/xml.js:36:20)
at writeValue (src/javaRosa/plugin.js:416:27)
at _instance.contributeToModelXML (src/javaRosa/plugin.js:455:29)
```
This bug was probably introduced in https://github.com/dimagi/Vellum/commit/6c95b1179963452d3a1b694cf2b1ca6bf278cca7#diff-07eb3730e4155b85f6aed124e86f5e4e485eba073d2019ffac83f7fef3fab313L1697-R1695 (translations were not …

Fix save form with new language and missing itext

---

package.json
src/main.js
yarn.lock

We recently upgraded most of the dev dependencies for `dimagi/js-xpath` due to security vulnerabilities. This bumps the version referenced in vellum to that new release/tag in our repo
All tests pass locally!
I think our tests are reliable enough that we would have caught any major issues, both in the xpath tests and in vellum specific tests.
Tests should cover any issues.

Upgrade js-xpath to 0.0.4

---

Makefile

HQ has ignored all `node_modules` directories anywhere in the repo for a very long time (at least 6 years). When vellum switched from `bower` to `yarn`, `manifest.txt` moved from `_build/bower_components/` to `_build/node_modules/`, and became ignored by HQ, which removed visibility on library versions changing with each vellum deploy.

Put manifest.txt in a place not ignored by HQ

---

src/expressionEditor.js
tests/expressionEditor.js

Changing the expression join type did not enable the save button.
Test added.
No QA.

Fix save button in XPath editor

---

package.json
yarn.lock

Address security warning that says we should be on at least grunt 1.3.0.
Ran tests and the build locally and everything passed, so I think we are good to go with this.
Yes
None needed as grunt is used for tests and the build
grunt is used for tests and the build

[dependency] ensure grunt resolves to at least 1.3.0

---

package.json
yarn.lock

A followup to [this PR](https://github.com/dimagi/Vellum/pull/1024). I didn't update `package.json` in js-xpath to v0.0.5, so it was unclear which version was being referenced by vellum. Rather than messing with updating the v0.0.5 tag on js-xpath, we decided to make a new version that properly updates package.json. All this PR is responsible for is referencing that new tag.

Update js-xpath to v0.0.6

---

package.json
yarn.lock

Similar to the upgrade in commcare-hq, this PR ensures that `getobject`, a sub-sub dependency of `grunt`, resolves to at least `1.0.0` to address a security vulnerability concern. If tests pass, that should be good enough to merge.
Yes
None
sub-sub dependency of `grunt`, so if tests pass this is good to go

[security] ensure getobject is at least v 1.0.0 due to security vulnerability

---

package.json
yarn.lock

Upgrade `http-server` to latest release (14.1.0) to remove `ecstatic` (discontinued) dependency.
- switches to approximate versioning
- removes (discontinued) `ecstatic` dependency
- removes `colors` dependency
Reviewed release history and looks safe. Most notable breaking change is drop of support for Node.js 10.
No tests (only used via the `testserver` script).
No QA.
Library is only used via package scripts (testserver) and is only invoked in the most basic way (not heavily configured). New version works fine out of the box and upgrade is safe.

Upgrade `http-server` from 0.12.3 to 14.1.0

---

README.md

Some small readme updates.
- Updates the build status badge to read from github actions
- Adds some pre-requisite hints for running tests locally (`node 14.x` and `npm 7.x` required)
Just updates to Readme

update readme with useful test hints and new status badge

---

package.json
yarn.lock

Sets the minimum version of `ansi-regex` to `4.1.1` based on this security alert:
https://github.com/dimagi/Vellum/security/dependabot/11
https://dimagi-dev.atlassian.net/browse/SAAS-13323
If build/tests pass, then we should be good.
Not needed with passing build
sub-sub dependency. if the build/tests pass then we're good.

set minimum resolution for ansi-regex to 4.1.1

---

.github/workflows/tests.yml

Followup to #1063. Make GitHub actions install a version of yarn that complies with the `yarn.lock` requirement.
GitHub actions (tests) only.
Tests only.

Install lock file version of yarn for GitHub actions tests

---

.github/workflows/metrics.yml
scripts/datadog-utils.sh
scripts/outdated-dependency-metrics.py
scripts/track-dependency-status.sh
scripts/yarn-list.py

Using the structure we have for tracking HQ dependencies, I've copied the relevant utilities to vellum (not my favorite solution) to push dependency metrics to Datadog. Metrics are pushed to Datadog with its own github action
N/A
Just metrics
Just Metrics

Track metrics for vellum dependencies

---

.github/workflows/tests.yml
package.json
yarn.lock

**Quick PR to update the ubuntu image to 22.04 in workflow for tests as 18.04 was deprecated from 4th April 2023.**
Also bumps dev dependency  `mocha-headless chrome` to `4.0.0` as after updaing the ubuntu version, tests won't run and gave this [error](https://github.com/dimagi/Vellum/actions/runs/4626644895/jobs/8183616118#step:5:1511).
Note: Did not spend much time investigating the error as updating the dependency resolved it. Noticed that the current puppeter version was quite outdated.

Update Ubuntu version to 22.04 in Github workflow for tests

---

.github/workflows/metrics.yml

Given development on Vellum is not the most active, we should trigger the vellum metrics workflow more than just on pull requests to master to ensure our dashboard in DataDog accurately reflects the state of Vellum dependencies.
No tests.
No QA
Only changes how often an existing workflow runs.

Trigger vellum metrics workflow daily

---

PLUGIN_DEVEOPMENT.md
README.md
src/commcareConnect.js
src/core.js
src/main.js
src/mugs.js
tests/.jshintrc
tests/commcareConnect.js
tests/main.js
tests/options.js
tests/static/commcareConnect/assessment.xml
tests/static/commcareConnect/learn_module.xml

A new plugin for CommCare Connect which adds two 'advanced' question types:
* Learn Module
* A question for recording metadata about a CommCare Connect learn module
* Contains static elements `name`, `description`, `time_estimate`
* Assessment Score
* A question for recording a user's assessment score.
The XML for the 'questions' is as follows:
```xml
<module xmlns="http://commcareconnect.com/data/v1/learn" id="intro_x">
<name>Introduction</name>
<description>An introduction to X</description>
<time_estimate>2</time_estimate>
</module>
<assessment xmlns="http://commcareconnect.com/data/v1/learn" id="pmtct_basic_v1">
<user_score>63</user_score>
</assessment>
```
More details in the spec: https://docs.google.com/document/d/1cImuUqpEzdXbgIaty8yX6-cRjHO4Tc92xvhNW7VbBxw/edit#heading=h.ubg1wxo6v …

CommCare Connect plugin

---

src/commcareConnect.js
tests/commcareConnect.js
tests/static/commcareConnect/assessment.xml
tests/static/commcareConnect/deliver.xml

Jira: https://dimagi-dev.atlassian.net/browse/CCPC-110
This adds a new 'mug' to the `commcareConnect` plugin which is used by CommCare Connect projects to track service delivery. A delivery unit XML block is added to a form that represents a unit of service delivery. When this form is forwarded to CommCare Connect, the details in the XML block are processed to record the service delivery.
```xml
<deliver xmlns="http://commcareconnect.com/data/v1/learn" id="unit_one">
<name>unit 1</name>
<entity_id>123123</entity_id>
<entity_name>23 Mvuramanga Road</entity_name>
</deliver>
```
CommCare Connect
Updated unit tests.
None
The changes are limited to the CommCare Connect plugin which is only enabled based on the FF. The changes have unit test coverage and were tested locally.

commcare connect deliver unit mug

---

Makefile

Attempting to fix building vellum on M1 machines. Updating path to r.js to reference the version in node_modules
yes
no
just affects the building of vellum. if the build no longer works as a result, we can revert this change. does not affect anything live on prod

update r.js path in build (so it works for M1 users)

---

package.json
yarn.lock

`yarn` was not able to detect a change in the `langcodes` submodule because no versioning was specified in `package.json`. This directs `yarn` to look at the `master` branch of the `langcodes` submodule
n/a
not needed
does not affect anything run in production. only would affect build / `yarn install`

specify master branch in dimagi/langcodes dependency so that yarn knows what version to look for

---

.github/workflows/metrics.yml
.github/workflows/tests.yml
package.json
yarn.lock

This removes the `yarn` pin from `package.json`. This is not good practice to do.
This needs to be done so that the `vellum-to-hq` command can finish packaging vellum for HQ
yes
no
safe. just updates dependency on `yarn`. tests will fail if this is a bad idea.

remove yarn pin from package.json

---

src/parser.js
tests/parser.js
tests/static/parser/body-group.xml

An extra read-only control node was added to the form when it was loaded, resulting in a broken form.
Yes.
Tested locally in a chromium-based browser and Firefox. Vellum automated test coverage is very good.

Fix bug caused by group named 'body'

---

package.json
yarn.lock

https://dimagi.atlassian.net/browse/SAAS-15983
HQ was done in https://github.com/dimagi/commcare-hq/pull/34917
There is test coverage, I'll also smoke test on staging.
no

Upgraded requirejs from 2.36 to 2.37

---

package.json
yarn.lock

...to relax dependency on requirejs so an outdated version can be eliminated.
Yes? Vellum has good test coverage, and it is likely that tests would reveal any issues with changing the version of requirejs used by requirejs-undertemplate.
This is a tiny change allowing requirejs-undertemplate to use newer versions of requirejs. The practical difference is that requirejs 2.3.7 is used everywhere now, and 2.3.3 is no longer used at all.

Upgrade requirejs-undertemplate

---

src/templates/atwho_display.html

https://dimagi.atlassian.net/browse/SAAS-16040
Atwho dropdowns have sometimes been displaying text in unexpected fonts:
This appears to be happening because the text is contained inside the icon's `<i>` tag:
Atwho has tests, though not of this kind of display behvior.
Not requesting QA.
Tiny change to correct malformed HTML, and risk should be limited to atwho dropdowns.

Fixed unexpected fonts displaying in atwho dropdowns

---

src/core.js

Same issue as https://github.com/dimagi/Vellum/pull/1135 just in a different place, causing unexpected fonts when viewing source XML:
https://dimagi.atlassian.net/browse/SAAS-16526
doubt it
no
Tiny change to correct malformed HTML.

Fixed font display in source XML

---

src/atwho.js

https://dimagi.atlassian.net/browse/SAAS-16391
This raises the limit from the [default](https://dimagi.atlassian.net/browse/SAAS-16391) of 5 to 10, which is the [same](https://github.com/dimagi/Vellum/blob/b193bd450901efd6e419f952f4e42548b037b175/src/atwho.js#L160) used for the question dropdown (this list of questions that shows up when you type `#form`). Ten is bigger than working memory (which is 5-7 items), so it's long enough that people are less likely to look at it, grasp all the items, and feel like something is missing.
Not of this behavior.
No.
Trivial config change.

Updated limit for non-question atwho widgets

---

src/logic.js
tests/logic.js

Invalid XPath expressions are now flagged with a warning message. Questions with warnings are highlighted in the question tree, and the save button displays an error on mouse-over.
https://dimagi.atlassian.net/browse/SAAS-16376
Yes.
Simply adds a warning when an XPath expression is not valid. Invalid XPath expressions were previously not highlighted in any special way, although the logic manager could not parse them.

Display warning for invalid XPath expression

---

src/form.js
src/logic.js
src/richText.js
tests/logic.js
tests/static/logic/hashtag-filter.xml

[Known limitation of js-xpath](https://github.com/dimagi/js-xpath?#known-limitations):
- Filter expressions are not supported due to a known bug in jison.
https://dimagi.atlassian.net/browse/SAAS-16886
Follow-up for https://github.com/dimagi/Vellum/pull/1138
Yes.
This workaround looks for a specific error that is thrown when js-xpath parser hits a known limitation with filtered hashtag expressions. An example of the error looks like
```
Error: Parse error on line 1:
count( #case/dob [1=1])
-----------------^
Expecting 'EOF', 'RPAREN', 'OR', 'AND', 'EQ', 'NEQ', 'LT', 'LTE', 'GT', 'GTE', 'PLUS', 'MINUS', 'MULT', 'DIV', 'MOD', 'UNION', 'COMMA', 'SLASH', 'RBRACK', got 'LBRACK'
```
It additionally checks the erroneous expression for filtered and escaped hashtag syntax. If both of those …

Avoid invalid XPath error on filtered hashtag

---

.github/workflows/metrics.yml
.github/workflows/tests.yml

https://dimagi.atlassian.net/browse/SAAS-17438
Cherry-picked from webpack migration, which adds `css-loader`, which requires node minimum 18.12.0. See [here](https://github.com/dimagi/Vellum/actions/runs/14499301585/job/40674880030) for a test run that failed on a proof of concept branch.
I also updated setup-node to v4 because that's what HQ does.
It is tests.
no
Only affects developer-facing workflows.

Upgraded version of node used in github actions

---

src/core.js
src/main.js
src/templates/confirm_overwrite.html
src/util.js
tests/core.js
tests/main.js
tests/static/core/diff-result.html
tests/static/core/diff1.xml
tests/static/core/diff2.xml

This replaces the usage of `jsdiff` in the "Show overwrite warning" popup with usage of `diff_match_patch`.
`jsdiff` is one of the few libraries that's only on bower, not npm, which means it's one of the libraries keeping Vellum on yarn. I was hoping to remove it altogether but didn't realize that it's also used in a [test utility](https://github.com/dimagi/Vellum/blob/c109eaa51f203c4e14b23add33d2d1042c763a4a/tests/utils.js#L110-L115) to create diffs for test results like XML snippets and text representations of jstree schemas.
This changes the look and feel of the diff. I think it's an improvement, but I'm biased.
Added in this PR
Not requesting QA
This is a limited change to a minor workflow, and it has test coverage.

Reduce usage of jsdiff

---

src/core.js

[Main PR](https://github.com/dimagi/commcare-hq/pull/36034)
Extra conditional that only allows Document uploads to be added to apps on version 2.57 and above.

Only allow Document widget to be added if minimum CC version is met

---

Makefile
test

Followup for https://github.com/dimagi/Vellum/pull/1155
I realized that depending on which config of webpack you've most recently run with, running tests may fail with an error about require not being defined. This PR makes sure that the proper build files are available when you run via either the `test` script or the Makefile.
It's all about tests.
It's tests.
No

Make sure that yarn is built properly before running tests

---

src/mugs.js
test
tests/mugs.js
tests/static/mugs/required-label.xml

Previously, removing the "minimal" appearance from a label question would cause the required fields (checkbox and conditional expression) to appear in its properties, and those properties could be updated and saved, but their values were cleared on reloading the question.
Required properties are now loaded properly for labels without "minimal" appearance. However, since "minimal" is the default appearance for labels, required properties are removed when a question's type is changed to Label.
https://dimagi.atlassian.net/browse/SAAS-11058
The second commit is an unrelated tweak to the test script.
Tested locally and with automated tests.
Yes.

Fix required properties on labels with non-minimal appearance
