src/core.js

https://github.com/dimagi/Vellum/pull/289#issuecomment-69028468

Change close to cancel

---

src/core.js
src/mugs.js
tests/options.js
tests/questionTypes.js
tests/static/all_question_types.tsv
tests/static/all_question_types.xml

Allows groups and repeat groups to be nodes under a field list
@ctsims Mobile supports this as of 2.16 correct?

Add group to field list

---

src/core.js

Also fix indentation.
http://manage.dimagi.com/default.asp?153548

Fix bug in Full Screen analytics

---

Makefile

Matches this: https://github.com/dimagi/Vellum/blob/f9cbcc5575c764f1fbd9a8c2e4b18fcf7bd34e56/Makefile#L17
@millerdev

Add PATH to bower list

---

tests/main.js

Allow reload last saved form after page reload in stand-alone/test mode

---

src/base.js
tests/base.js
tests/main.js

Ignore unknown plugins (rather than crashing)

---

src/core.js

http://manage.dimagi.com/default.asp?75697#858316
@millerdev

Reset error messages after question deletion

---

src/core.js
tests/core.js

http://manage.dimagi.com/default.asp?153400#858786

Item in collapsed

---

src/core.js
src/form.js
tests/core.js

http://manage.dimagi.com/default.asp?116075#841220
Choice values shouldn't have the same value and different labels
@millerdev

Disallow duplicate choice

---

src/mugs.js
tests/questionTypes.js
tests/static/all_question_types.tsv
tests/static/all_question_types.xml
tests/static/profiling/small-form.xml

[3:24:33 PM] Andrea Fletcher: is there ever a time when you would want group questions to be required?
[3:24:45 PM] Andrea Fletcher: does checking that box break things? It seems to....
[3:25:09 PM] Clayton Sims: group questions cannot be required
[3:25:20 PM] Clayton Sims: the UI will not enforce any constraints if you set them to be

Don't allow group questions to be required

---

src/core.js
src/javaRosa.js
src/mugs.js
tests/javaRosa.js

http://manage.dimagi.com/default.asp?109902
Now displays as "DefaultLanguageLabel [en]"

Append language code when showing default instead of selected

---

src/core.js

http://manage.dimagi.com/default.asp?59401

Focus on ID when adding new question

---

tests/javaRosa.js

Test for https://github.com/dimagi/Vellum/pull/294

Testing "Question ID" option in languages dropdown

---

src/widgets.js

http://manage.dimagi.com/default.asp?61268
Tested in Chrome and Firefox. Not a great candidate for automated testing.

Steady cursor when replacing spaces with underscores

---

src/core.js
tests/core.js

Fix save button activation on load form

---

src/core.js
src/mugs.js
tests/javaRosa.js

http://manage.dimagi.com/default.asp?155532

Drop longs

---

src/widgets.js
tests/main.js
tests/widgets.js

http://manage.dimagi.com/default.asp?157728
This bug was introduced by https://github.com/dimagi/Vellum/commit/1cf6eb559f9937b6705b594ce2fa0f99c1bf3966

Make XPath widget properly handle newlines

---

src/javaRosa.js
src/mugs.js

http://manage.dimagi.com/default.asp?156179#875788
Tried to write out a test for this, but for some reason the save button wouldn't be triggered in the test. (tried both $("[name='property-helpItextID']").val('blah') and text.p.helpItextID.id = 'blah')

Change save button if id changes

---

src/form.js
src/util.js
tests/form.js

http://manage.dimagi.com/default.asp?158002#878245

Repeat count reference

---

src/datasources.js
src/modeliteration.js
tests/modeliteration.js

Fix bugs in data source instance tracking

---

src/mugs.js
tests/form.js

http://manage.dimagi.com/default.asp?116075

Warn on same choice value

---

src/javaRosa.js
tests/options.js

Remove help text feature flag

---

src/core.js
src/form.js
src/intentManager.js
src/javaRosa.js
src/parser.js
src/tree.js
src/util.js
src/writer.js
tests/form.js
tests/static/all_question_types.tsv
tests/static/form/hidden-value-tree-order.xml
tests/static/form/mismatch-tree-order.xml

No longer have to keep track of both the data and control tree.
The control tree is the master and we use the flags isControlOnly and isDataOnly whenever we need to discern between those.

Only one tree

---

src/commtrack.js
tests/commtrack.js

http://manage.dimagi.com/default.asp?158056
@czue @emord

Omit src or dest from transfer when empty

---

src/commtrack.js
src/writer.js
tests/commtrack.js

Remove pre-existing src/dest attribute from the data node when value its removed.
http://manage.dimagi.com/default.asp?158056
@czue @emord

Fix transfer src/dest attribute writing

---

src/javaRosa.js
src/uploader.js

http://manage.dimagi.com/default.asp?141505#885219
No tests for this as it's more about vellum interacting with mediauploader. Fixes it to change it to Replace Video and no longer has the wrong file type error

Return value or placeholder

---

src/core.js
src/javaRosa.js
src/widgets.js
tests/commtrack.js
tests/javaRosa.js
tests/utils.js

http://manage.dimagi.com/default.asp?158065
Not 100% happy with this as it fires two change events for most mug property changes. However, the alternatives seem worse.
@emord

Activate save button on widget change

---

src/mugs.js

Escaping the mugs display name 
The fun things you can do without this:

Escape mug display name

---

src/javaRosa.js
src/parser.js
src/util.js
src/xml.js
tests/javaRosa.js
tests/main.js
tests/static/javaRosa/outputref-with-inequality.xml
tests/xml.js

http://manage.dimagi.com/default.asp?158705

Improve XML normalization

---

src/core.js
src/form.js
src/logic.js
src/mugs.js
src/parser.js
src/tree.js
src/util.js
src/writer.js
tests/diffDataParent.js
tests/form.js
tests/main.js
tests/questionTypes.js
tests/static/diffDataParent/data-parent-mug-after.xml
tests/static/diffDataParent/data-parent-mug-before.xml
tests/static/diffDataParent/data-parent-mug-in-between.xml
tests/static/diffDataParent/parse.xml
tests/static/diffDataParent/sibling-as-child.xml
tests/utils.js

@millerdev 
Had to add a couple of commits at the end to fix tests, but mostly just rebased on master

Non group child2

---

src/xml.js
tests/xml.js

http://manage.dimagi.com/default.asp?122203
http://manage.dimagi.com/default.asp?159671

Work around XML escaping bug in browser

---

src/commtrack.js
src/form.js
src/modeliteration.js
tests/commtrack.js
tests/modeliteration.js
tests/static/commtrack/balance-block.xml
tests/static/commtrack/transfer-block.xml
tests/utils.js

http://manage.dimagi.com/default.asp?158681
@czue @emord

Add a ledgerdb instance for balance/transfer questions

---

src/commtrack.js

Define commtrack ledger constants

---

src/mugs.js
tests/javaRosa.js
tests/static/javaRosa/group-help.xml
tests/static/javaRosa/select1-help.xml

http://manage.dimagi.com/default.asp?161354
@czue

Do not write duplicate help for group/select

---

bower.json
src/core.js
src/main.js
src/templates/confirm_overwrite.html
src/util.js
tests/main.js

@millerdev 
Making this diff pretty with green/red colors will probably be a PITA, but this has all the info one would need right now

Diff on overwrite

---

src/core.js
src/mugs.js
tests/core.js

http://manage.dimagi.com/default.asp?162873

Do not show Choice in type changer menu

---

src/javaRosa.js
src/mugs.js
tests/core.js
tests/javaRosa.js

Try to clean up one little thing in javaRosa and you get sucked into a rabbit hole that never ends. One of these days I'll get to the bottom.

Fix stand-alone mode and Itext validation

---

src/core.js
src/form.js
src/javaRosa.js
src/mugs.js
src/uploader.js
src/writer.js
tests/javaRosa.js
tests/modeliteration.js
tests/utils.js

This includes a bugfix for an issue that to my knowledge has not been reported in FogBugz yet, but was discussed earlier today on Global Field/Dev Chat.
Possibly easier to review commit by commit.

javaRosa fixes and cleanup

---

src/core.js
src/mugs.js
src/polyfills.js
tests/main.js

Minor stuff

---

src/core.js
src/mugs.js

Only moving code, no new features.
- Group error handling functions in core.js
- Move Mug class to top of mugs.js
Aside: this is merging into `copy-paste-dev` which is a branch I'll be submitting copy-paste-related PRs against. This allows me to get sub-features up for PR without having to hold off forever on merging into master.

Move stuff around

---

src/templates/xpath.html

http://manage.dimagi.com/default.asp?164607

Make advanced XPath warning less intimidating

---

src/templates/multimedia_modal.html

http://manage.dimagi.com/default.asp?142336

drop checkbox from within formbuilder

---

src/commtrack.js
src/core.js
src/form.js
src/javaRosa.js
src/less-style/structure.less
src/logic.js
src/mugs.js
src/parser.js
src/templates/widget_control_message.html
src/util.js
src/widgets.js
tests/commtrack.js
tests/core.js
tests/form.js
tests/itemset.js
tests/javaRosa.js
tests/logic.js
tests/main.js
tests/modeliteration.js
tests/static/commtrack/invalid-transfer.xml
tests/utils.js

Refactor mug messaging system to show messages inline, often beside the widget where the error occurred, although this could be improved in some cases. This should be a huge usability improvement.
Note: merging into copy-paste-dev branch, not master.
@emord @benrudolph

Mug messages

---

src/javaRosa.js
tests/javaRosa.js
tests/static/markdown/no-markdown.xml
tests/static/markdown/with-markdown.xml

http://manage.dimagi.com/default.asp?166113#924497
Wasn't adding markdown forms to help itext that already existed
enchantress: @snopoke

Fix markdown

---

src/core.js
tests/core.js

Looks broken to have a big blank space when you delete the last question in a form.
@nickpell

Welcome panel

---

src/commtrack.js
tests/commtrack.js
tests/static/commtrack/balance-block.xml
tests/static/commtrack/transfer-block.xml

Add is-relevant to transaction questions

---

src/core.js
src/mugs.js

- Group error handling functions in core.js
- Move Mug class to top of mugs.js
This was cherry-picked from the copy-paste-dev (e0fef536473f678480d5206d628f3d2e15a78b0a), and it should make merges easier.
@emord @orangejenny 
cc @benrudolph

Move code around

---

src/core.js
src/javaRosa.js
src/mugs.js
src/util.js
src/widgets.js
tests/core.js
tests/widgets.js

Click the X to dismiss the error...
Additionally, I attempted to clean up event unbinding. The API is a little gnarly, but at least it's documented.
Merging into copy-paste-dev
@emord 
cc @benrudolph

Resolve conflicted question ID on dismiss duplicate ID error

---

src/javaRosa.js

http://manage.dimagi.com/default.asp?166307
Cherry-picked from https://github.com/dimagi/Vellum/pull/388, as that's on copy-paste-dev and likely won't make it to HQ for a while.
@emord 
cc @benrudolph

Fix focus on tab into label widget

---

src/javaRosa.js

http://manage.dimagi.com/default.asp?166357
I originally took this out so that there wouldn't be another box that showed up somewhat randomly, but it had the unintended side effect described above.
@orangejenny @millerdev

Show custom box for markdown

---

src/util.js

screwed up regex here.
https://github.com/dimagi/Vellum/pull/387/files
@millerdev 
Tests will come. but want to deploy soon

Fix node id regex

---

src/core.js
src/javaRosa.js
src/mugs.js
src/parser.js
src/writer.js

Add `Mug.getPresence(property)` and `Mug.isVisible(property)`
@emord

Mug refactor

---

src/javaRosa.js
tests/javaRosa.js
tests/static/javaRosa/no-label-text-one-lang.xml

http://manage.dimagi.com/default.asp?166694#929816
Functionality changed here https://github.com/dimagi/Vellum/commit/5b0954416ca1a3c6b4ff17c37e5d3197bfd910ed
for no apparent reason.
@millerdev

Always write value on labels

---

src/javaRosa.js

I don't even...
http://manage.dimagi.com/default.asp?166645
@emord

Increment to prevent infinite loop

---

src/templates/widget_control_keyvalue.html

http://manage.dimagi.com/default.asp?164693
@emord

Allow drag/drop question into App Callout value

---

tests/javaRosa.js

https://github.com/dimagi/Vellum/pull/392
@millerdev The tests as promised
@snopoke

Test valid/invalid itext ids

---

src/parser.js
tests/parser.js
tests/static/parser/missing-bind.xml

http://manage.dimagi.com/default.asp?167660
cc @NoahCarnahan @ctsims

Fix error on load question without bind element

---

src/mugs.js
tests/form.js
tests/main.js
tests/mugs.js

http://manage.dimagi.com/default.asp?163258
Merging into copy-paste-dev. Went a little crazy with refactoring on this one. Still fleshing out the new mug messages framework.
cc @NoahCarnahan

Warn about top-level question (not in group) named case

---

src/mugs.js
tests/questionTypes.js

http://manage.dimagi.com/default.asp?160006
cc @NoahCarnahan

Fix media capture question type changer

---

src/javaRosa.js
src/uploader.js
src/widgets.js
tests/copy-paste.js

http://manage.dimagi.com/default.asp?166872
http://manage.dimagi.com/default.asp?166978
cc @kaapstorm

Fix copy paste issues found during QA

---

src/ignoreButRetain.js
src/mugs.js
tests/formdesigner.ignoreButRetain.js
tests/static/ignoreButRetain/unknown-element.xml

http://manage.dimagi.com/default.asp?167882
cc @kaapstorm

Fix crash on load form with unknown element

---

src/commtrack.js
src/core.js
src/parser.js
tests/commtrack.js
tests/core.js
tests/static/commtrack/balance-block.xml
tests/static/commtrack/transfer-block.xml

https://trello.com/c/HYmHNRua
cc @kaapstorm

Supply: Receive/Dispense question types

---

src/copy-paste.js
src/core.js
src/mugs.js
src/templates/copy_paste_help.html
tests/copy-paste.js

Three changes, three commits. Merging into copy-paste-dev
cc @kaapstorm

Pre UAT copy paste changes

---

src/copy-paste.js
src/less-style/question-props.less
src/templates/copy_paste_help.html

Tweak copy/paste help layout

---

src/commtrack.js
tests/static/commtrack/balance-block.xml
tests/static/commtrack/transfer-block.xml

http://manage.dimagi.com/default.asp?168205
cc @orangejenny @kaapstorm

Fix relevancy bind on transaction question types

---

src/copy-paste.js
src/core.js
src/less-style/editor-column.less
src/templates/copy_paste_help.html
src/templates/main.html
src/templates/question_toolbar.html
tests/itemset.js

https://docs.google.com/spreadsheets/d/1ZjhMFP-QLE_MmSZZsIHwbL2C1HLZUYRkAiiqUyX25F4/edit#gid=0
Merging into copy-paste-dev
cc @amsagoff @kaapstorm

Copy/paste UAT feedback

---

src/javaRosa.js
tests/static/javaRosa/no-label-text-one-lang.xml

https://github.com/dimagi/Vellum/pull/396#issuecomment-97542601
elf: @czue

Fix no placeholder

---

src/itemset.js
tests/advancedItemsets.js
tests/main.js
tests/options.js

Revived this from before itemset-connector-2 was merged. Uses the same tests as well
@millerdev elf: @czue

Revive advanced itemsets

---

src/copy-paste.js
src/javaRosa.js
tests/copy-paste.js

- [Fix bug in ordering of pasted questions](http://manage.dimagi.com/default.asp?168666)
- [Warn on paste missing multimedia](http://manage.dimagi.com/default.asp?168667)
cc @sravfeyn

Copy paste QA fixes

---

src/datasources.js
src/itemset.js
tests/advancedItemsets.js
tests/itemset.js
tests/options.js

Spike on https://github.com/dimagi/Vellum/pull/417
@emord 
cc @kaapstorm

Add advanced editor to fixture widget (flagged)

---

src/javaRosa.js
tests/javaRosa.js

http://manage.dimagi.com/default.asp?168791
This bug was found during copy/paste QA, but applies to master as well.
cc @sravfeyn

Fix infinite loop in bulk translation updater

---

src/javaRosa.js
src/mugs.js
src/widgets.js
tests/copy-paste.js
tests/javaRosa.js
tests/questionTypes.js

http://manage.dimagi.com/default.asp?168791
http://manage.dimagi.com/default.asp?168800
cc @sravfeyn

Fixes for more bugs found in QA

---

src/copy-paste.js
src/core.js
tests/copy-paste.js

http://manage.dimagi.com/default.asp?168666
cc @sravfeyn

Paste after last selected question

---

src/copy-paste.js
src/core.js
src/expressionEditor.js
src/form.js
src/widgets.js

- Add/update analytics events for copy/paste.
- Switch to new analytics API.
Depends on https://github.com/dimagi/commcare-hq/pull/6787
cc @sravfeyn

Update analytics tracking events

---

src/datasources.js

@millerdev Did I miss anything? I don't think this changes too much in your generalization branch
@czue A little context from the earlier email
enchantress: @esoergel

Document datasources

---

src/itemset.js
tests/itemset.js

http://manage.dimagi.com/default.asp?168793
@esoergel

Ignore filters in itemset values and labels

---

build.js

Bundle atwho.css

---

src/datasources.js
src/itemset.js
src/widgets.js
src/window.js
tests/datasources.js
tests/itemset.js
tests/options.js
tests/utils.js

Also clean up window manager. All of this work is pre-req for case management.
@emord 
cc @sravfeyn

Async data source improvements

---

src/copy-paste.js

http://manage.dimagi.com/default.asp?169570#949638
@millerdev @esoergel

Enable copy/paste for non mac firefox users

---

src/core.js

some ui refactoring, in the hope that we can get off jQuery UI altogether soon
Old:
New:

Dialog jQuery UI => bootstrap

---

src/core.js

another https://github.com/dimagi/Vellum/pull/433
@proteusvacuum

Another dialog

---

src/core.js
src/javaRosa.js
src/templates/main.html
src/templates/modal_content.html
tests/utils.js

get rid of the last of the jQuery UI dialogs
@proteusvacuum

Last dialogs

---

src/core.js
src/expressionEditor.js
src/itemset.js
src/javaRosa.js
src/less-style/question-props.less
src/util.js
src/widgets.js

Release the  question shortcut. The key is `/data/`
Analytics are:
Category | Action | Label | Description
-----------|---------|----------|------------
Question Reference |	Drag n Drop vs. Autocomplete	|display condition vs. validation condition|	Question reference created via either autocomplete or drag n drop (not direct writing)
Output Value|	Drag n Drop vs. Autocomplete|	date format|	Output value created via autocomplete or drag n drop
cc @gcapalbo

Question shortcut

---

src/core.js

close edit XML dialog on save

---

src/itemset.js

replace itemset autocomplete with at.js

---

src/core.js
src/expressionEditor.js
src/javaRosa.js
src/util.js
src/widgets.js

https://github.com/dimagi/Vellum/pull/444#discussion_r32084248
jquery ui autocomplete in the expressoin editor for itemsets also has the same issue, but those will probably get replaced with at who soon
cc: @gcapalbo

Cleanup atwho containers

---

src/copy-paste.js

The count was not being sent to Kiss
cc @amsagoff

Fix bad analytics API usage

---

bower.json
src/itemset.js
src/util.js

At.js: use tabSelectsMatch

---

src/expressionEditor.js
src/itemset.js
src/util.js

Will actually drop jQuery UI in another PR, not enough time to finish that right now.
@sravfeyn / @emord

Convert last autocomplete to use at.js

---

src/commtrack.js
src/core.js
src/less-style/question-props.less
src/templates/question_fieldset.html
src/util.js
src/widgets.js

http://manage.dimagi.com/default.asp?170957
Should wait on the [corresponding HQ PR](https://github.com/dimagi/commcare-hq/pull/7126).
@sravfeyn / @emord 
cc @amsagoff

Help on focus

---

src/util.js

include icon in dropdown

---

src/javaRosa.js
tests/javaRosa.js

http://manage.dimagi.com/default.asp?172565
@emord 

Unlink shared itext on set auto itext ID

---

src/javaRosa.js
tests/javaRosa.js
tests/static/javaRosa/no-label-text-one-lang.xml

http://manage.dimagi.com/default.asp?169124#959318
@millerdev 
@biyeun

No placeholder

---

src/jquery-extensions.js
src/parser.js
src/util.js
src/window.js

This did not break prod or staging because jquery-ui is loaded by HQ.
@orangejenny 

Fix draggable divider since jquery-ui removal

---

src/javaRosa.js
tests/static/all_question_types.xml
tests/static/javaRosa/test-xml-2.xml

Add media to validation messages
@millerdev 
cc: @biyeun

Validation media

---

src/core.js
src/javaRosa.js
tests/javaRosa.js

Delegate handle drop to the tree node so we can drag from different types of trees (in the future). This refactor is preparation for case management.

Refactor drag/drop API to be more generic

---

index.html
tests/main.js

upload xml file in standalone

---

src/javaRosa.js
tests/javaRosa.js

http://manage.dimagi.com/default.asp?173827
Seems silly that we don't use the same format as HQ. 
cc: @biyeun

Use _ in export translations

---

src/datasources.js
src/expressionEditor.js
src/form.js
src/itemset.js
src/util.js
src/widgets.js
tests/datasources.js
tests/options.js
tests/utils.js

Clean up async code and update to new data sources API in preparation for case management.
Depends on https://github.com/dimagi/commcare-hq/pull/7254

Refactor async data sources

---

src/util.js

no functionality change. just a little nicer syntax
cc: @biyeun

nicer displayTpl

---

src/javaRosa.js
tests/copy-paste.js

http://manage.dimagi.com/default.asp?174407
This is another side-effect of allowing empty itext.
@emord

Fix paste empty itext

---

src/javaRosa.js
tests/copy-paste.js

http://manage.dimagi.com/default.asp?174407 strikes again

Fix paste with multimedia

---

src/core.js
src/javaRosa.js
tests/core.js

https://github.com/dimagi/Vellum/pull/467/files#r33373683
@emord 

Drop unused argument

---

src/javaRosa.js

http://manage.dimagi.com/default.asp?174085
cc: @gcapalbo

Don't show markdown for groups

---

Makefile

Fix css image locations in build output

---

.travis.yml
package.json

mocha-phantomjs v4.0.0-beta was released recently, and it broke the build.
cc @kaapstorm 
Wait for tests.

Fix failing build

---

.travis.yml
package.json

Reverts dimagi/Vellum#481 - not sure if this is fixed yet

Revert "Fix failing build"

---

src/core.js

A FM mentioned that this would ease the process of editing large forms with lots of groups.
cc @kaapstorm

Alt+Click tree node to expand/collapse all children

---

src/mugs.js
tests/questionTypes.js

Do not show required checkbox for minimal label

---

src/logic.js
src/util.js
tests/logic.js

Introduced here: https://github.com/dimagi/Vellum/pull/485
@orangejenny 
code buddy @gcapalbo

Validation conditions can have self references

---

src/logic.js
tests/logic.js

https://github.com/dimagi/Vellum/pull/488.
More tests as promised
@orangejenny @millerdev

Add tests for logic module

---

src/mugs.js

https://github.com/dimagi/js-xpath/pull/3
@emord

Fix bug introduced by xpath parser update

---

src/javaRosa.js
src/mugs.js
src/parser.js
src/writer.js
tests/questionTypes.js
tests/static/all_question_types.xml

Quote from @ctsims "jr:preload is not supported and we should remove it from both the documentation and from the form builder."
cc @kaapstorm @amsagoff

Remove unsupported jr:preload stuff

---

src/databrowser.js
src/less-style/structure.less
src/less-style/tree-content.less
src/templates/main.html
src/window.js

See commit messages for a description of what changed
<sub>(why do I feel the need to point that out, and a little silly for doing so at the same time?)</sub>
@emord 
cc @kaapstorm

App Resources style

---

tests/static/ignoreButRetain/unknown-element.xml

Fix test failing in Chrome: invalid XML

---

package.json
src/core.js

http://manage.dimagi.com/default.asp?176493

hide spinner on save

---

src/less-style/structure.less

http://manage.dimagi.com/default.asp?176624

Fix cursor in question tree menu

---

src/core.js
src/intentManager.js
src/less-style/question-props.less
src/templates/intent_templates.html
tests/intentManager.js
tests/options.js

This will show an empty templates selector until we get HQ to supply them in the vellum options. I'm working on that next.
cc @sravfeyn @wspride

Add templates to app callout question type

---

src/databrowser.js
src/templates/external_sources_tree.html

- Rename "App Resources" to "Case Properties"
- On form load, "Case Properties" window expanded by default
@emord 
cc @sravfeyn

Case management tweaks

---

src/intentManager.js
tests/static/intentManager/printing-intent.xml

Fix printing

---

src/intentManager.js
tests/static/intentManager/printing-intent.xml

Changing the printing reference to a string literal
https://github.com/dimagi/commcare-hq/pull/7764
cc @gcapalbo @kaapstorm

use literal string for file reference

---

bower.json
src/commtrack.js
src/saveToCase.js
tests/commtrack.js
tests/static/commtrack/balance-block.xml
tests/static/commtrack/invalid-transfer.xml
tests/static/commtrack/transfer-block.xml

http://manage.dimagi.com/default.asp?178707
@czue Should people using commtrack questions rebuild their forms/be told about this change?
cc: @gcapalbo @kaapstorm

Dont use today

---

src/saveToCase.js
tests/saveToCase.js

Save to case questions use binds instead of setvalues when inside a repeat
http://manage.dimagi.com/default.asp?179598
@sheelio 
buddies @proteusvacuum @esoergel

@case_id inserts into bind list inside repeat

---

src/saveToCase.js
tests/static/saveToCase/attachment_property.xml
tests/static/saveToCase/close_property.xml
tests/static/saveToCase/create_2_property.xml
tests/static/saveToCase/create_property.xml
tests/static/saveToCase/index_property.xml
tests/static/saveToCase/update_property.xml

http://manage.dimagi.com/default.asp?179830
@emord 
cc @TylerSheffels

apply case XMLNS to case node and all children

---

src/templates/markdown_help.html

http://manage.dimagi.com/default.asp?179872
buddy: @czue

Change markdown help text

---

src/less-style/structure.less
src/window.js

http://manage.dimagi.com/default.asp?179699
code buddies: @proteusvacuum @esoergel

Show date drag and drop on full screen

---

src/less-style/structure.less

http://manage.dimagi.com/default.asp?180562
cc: @czue

fullscreen covers footer

---

src/javaRosa.js
tests/markdown.js

http://manage.dimagi.com/default.asp?180582#1004456
cc @czue

Enable save button on toggle markdown

---

src/saveToCase.js

already used in icds. #4 here http://manage.dimagi.com/default.asp?180678#1004788
cc: @czue

Allow numbers in case property

---

src/intentManager.js
tests/options.js

dependent on https://github.com/dimagi/commcare-hq/pull/8089
cc: @czue

feature flag intents

---

src/mugs.js
tests/itemset.js
tests/static/itemset/test1-with-constraint.xml

http://manage.dimagi.com/default.asp?181208
cc: @czue

support itemsets with constraints

---

src/core.js
src/javaRosa.js
src/parser.js
src/writer.js
tests/markdown.js
tests/static/markdown/explicit-no-markdown.xml

http://manage.dimagi.com/default.asp?179722#1006121
disable markdown in form properties
@orangejenny @kaapstorm

Disable markdown

---

src/util.js
tests/javaRosa.js

http://manage.dimagi.com/default.asp?182112
@TylerSheffels 
@orangejenny @kaapstorm

Escape > in itext ids

---

src/core.js
src/mugs.js
src/parser.js
src/widgets.js
tests/options.js
tests/questionTypes.js
tests/static/all_question_types.xml
tests/static/questionTypes/image-capture.xml

http://manage.dimagi.com/default.asp?181411#1010439
Still needs to be version flagged, but this is most of it
@orangejenny @kaapstorm

Image resizer

---

src/itemset.js
src/logic.js
tests/itemset.js
tests/logic.js
tests/options.js
tests/static/itemset/data-itemset.xml

http://manage.dimagi.com/default.asp?180879#1012374
http://manage.dimagi.com/default.asp?180880#1012373
@TylerSheffels

Small fixes

---

src/expressionEditor.js

http://manage.dimagi.com/default.asp?182308#1014978
introduced during a refactor https://github.com/dimagi/Vellum/pull/468
(no test coverage for at.js related stuff... need to think about how to fix that)
@orangejenny cc: @TylerSheffels

Fix dropdown

---

src/itemset.js
tests/itemset.js
tests/options.js

http://manage.dimagi.com/default.asp?178265#1001988
Warns the user when we find an itemset on a community project
@dimagi/product how does this look?
@orangejenny 

Add lookup tables feature flag

---

src/mugs.js
tests/logic.js

http://manage.dimagi.com/default.asp?182818#1017622
@TylerSheffels

Require repeat_count

---

src/javaRosa.js
tests/options.js

https://github.com/dimagi/commcare-odk/pull/389
2.23 released

Support markdown in groups

---

src/mugs.js
tests/itemset.js
tests/static/itemset/test1-with-appearance.xml
tests/static/itemset/test1.xml

http://manage.dimagi.com/default.asp?182841#1018574

Allow appearance to be copied on selects

---

src/javaRosa.js

http://dimagi.uservoice.com/forums/176376-form-builder/suggestions/4412064-ability-to-use-output-ref-output-value-in-the-hint
This has worked for all itexts for a while. Just adding drag and drop for it.

Drag n drop

---

src/core.js
src/form.js
src/javaRosa.js
src/mugs.js
src/parser.js
tests/copy-paste.js
tests/core.js
tests/form.js
tests/javaRosa.js
tests/questionTypes.js
tests/static/all_question_types.tsv
tests/static/all_question_types.xml
tests/static/core/increment-item.xml
tests/static/javaRosa/itext-item-rename.xml

http://manage.dimagi.com/default.asp?89892#1012375
Makes item1, item2, ... into choice1, choice2, .... by default
@amsagoff 

choice -> item as default

---

src/javaRosa.js

Media section showing for hidden questions

---

src/atwho.js
src/itemset.js
src/widgets.js
tests/advancedItemsets.js
tests/datasources.js
tests/itemset.js
tests/options.js

http://manage.dimagi.com/default.asp?182309#1019420
This turns references into real mug properties instead of being attached to the dropdown.
It's a little bit of a departure from standard vellum as the content of the dropdown affects other properties, but it's necessary for the dropdown to work properly if the dropdown changes.
@orangejenny 

Itemset refactor

---

src/mugs.js
tests/logic.js
tests/questionTypes.js

http://manage.dimagi.com/default.asp?183425#1022284
@phillipm 

Repeat count required

---

src/itemset.js

@orangejenny feedback from the PR

remove unnecessary getuielement override

---

src/modeliteration.js
tests/modeliteration.js

http://manage.dimagi.com/default.asp?183996
@orangejenny 
cc @snopoke @ctsims

Fix setvalues in nested model iteration

---

build.js
lib/bootstrap-stickyover.js
src/databrowser.js
src/less-style/labels.less
src/less-style/main.less
src/less-style/popover.less
src/less-style/structure.less
src/main.js
src/richText.js
src/templates/external_sources_tree.html
src/util.js
src/widgets.js

@millerdev @emord 
@dimagi/product

Case Management Styling

---

src/less-style/labels.less

bubble text shouldn't be bold

---

src/atwho.js
src/javaRosa.js

http://manage.dimagi.com/default.asp?185094
@millerdev 
cc @NoahCarnahan

Display autocomplete options in form's current language

---

src/javaRosa.js
tests/javaRosa.js

http://manage.dimagi.com/default.asp?185830
@orangejenny cc @kaapstorm

Improve markdown detection

---

src/databrowser.js

http://manage.dimagi.com/default.asp?185759

Don't scroll if the pane is smaller than the head

---

buildmain.py
src/atwho.js
src/core.js
src/expressionEditor.js
src/javaRosa.js
src/less-style/question-props.less
src/mugs.js
src/richText.js
src/widgets.js
tests/richText.js
tests/utils.js
tests/widgets.js

http://manage.dimagi.com/default.asp?184602
Best reviewed by commit.
@orangejenny 
cc @emord (you should review this when you get back from vacation)

Fix newlines being eaten by rich text widget

---

src/atwho.js
src/widgets.js
tests/javaRosa.js

http://manage.dimagi.com/default.asp?186079#1038186
@millerdev

Only highlight on tab

---

src/core.js
tests/core.js

http://manage.dimagi.com/default.asp?185330
@emord

Use single quotes to wrap choice values

---

src/richText.js
tests/richText.js
tests/widgets.js

http://manage.dimagi.com/default.asp?185791
This actually fixes two bugs. Unfortunately I could not come up with a way to reproduce the CKEditor selection bug in an automated test, so I had to test it manually.
@emord cc @sravfeyn

Work around CKEditor selection bug

---

src/mugs.js
tests/setvalue.js

http://manage.dimagi.com/default.asp?184259
Don't really like this solution, but it'll take a little longer to make messages have different levels warnings/error/info. It's next up on my PID list.
cc: @gcapalbo

Provide help message instead of warning

---

src/javaRosa.js
src/widgets.js
tests/richText.js

@millerdev 
Easier to view the test changes ignoring whitespace

Markdown with rich text

---

src/parser.js
tests/parser.js

https://groups.google.com/forum/#!topic/commcare-users/uPdIy-9SQUk

Don't show data value when there isn't one defined

---

src/intentManager.js

No longer hide the extra response from print templates
cc: @amstone326 @benrudolph

Show responses  for print question

---

src/richText.js

https://github.com/dimagi/Vellum/pull/567#issuecomment-159013719

remove close button on bubbles

---

src/databrowser.js

http://manage.dimagi.com/default.asp?187360#1050522

case pane is 33% height

---

src/datasourcewidgets.js
tests/itemset.js

http://manage.dimagi.com/default.asp?188072

Fix lookup table config with no lookup tables

---

src/richText.js
tests/richText.js
tests/static/richText/burpee.xml

http://manage.dimagi.com/default.asp?188202

Escape output value

---

src/less-style/lib/variables.less
src/less-style/structure.less

http://manage.dimagi.com/default.asp?188390
code buddy @TylerSheffels

hide scrollbar for databrowser

---

src/atwho.js
src/util.js
tests/atwho.js
tests/main.js

Was a little hesitant changing some things with atwho, so decided to write some tests for it.
buddy: @TylerSheffels

Atwho tests

---

src/atwho.js
tests/atwho.js

PR #582 feedback

---

src/richText.js
tests/richText.js

http://manage.dimagi.com/default.asp?188772#1055825
@orangejenny 

Properly display mugs with unknown functions

---

src/richText.js
tests/richText.js

And humanize XML (`<output></output>` -> `<output />`).
See also https://github.com/dimagi/Vellum/pull/584
@emord

Remove span tag around unrecognized output value

---

src/core.js

Suggestion from field-dev
code buddy @TylerSheffels

Better error message

---

src/richText.js

https://github.com/dimagi/Vellum/pull/585/files#r47102044
@emord

Rich text refactor: xml.humanize -> xml.normalize

---

src/javaRosa.js
src/templates/language_selector.html
tests/javaRosa.js

http://manage.dimagi.com/default.asp?189183#1059677

remove display before adding new one

---

src/databrowser.js

minimum case property for databrowser

---

src/commtrack.js
src/core.js
src/exporter.js
src/form.js
src/javaRosa.js
src/logic.js
src/modeliteration.js
src/mugs.js
src/writer.js

Refactor all of the random places that break the mug barrier when getting absolute path
cc: @esoergel

absolutePath refactor

---

src/core.js
src/expressionEditor.js
src/javaRosa.js
src/logic.js
src/parser.js
src/richText.js
src/xpath.js

Clean up xpath module

---

src/javaRosa.js
tests/markdown.js

http://manage.dimagi.com/default.asp?189603
cc: @esoergel

add parens to ordered list

---

.travis.yml
bower.json
src/core.js
src/expressionEditor.js
src/form.js
src/javaRosa.js
src/logic.js
src/main.js
src/mugs.js
src/parser.js
src/richText.js
src/xpath.js
tests/logic.js
tests/richText.js

@millerdev
Makes the xpath parser an attribute of a form.
Depends on https://github.com/dimagi/js-xpath/pull/10
cc: @sravfeyn

Encapsulated xpath

---

src/mugs.js
tests/questionTypes.js

http://manage.dimagi.com/default.asp?209488
cc: @sravfeyn

Remove appearance attribute when changing mug from a label

---

bower.json
src/itemset.js
src/main.js
tests/questionTypes.js

http://manage.dimagi.com/default.asp?191099#1079355
@dimagi/product implements moving from select to lookup table, but not the other way around because you can't delete "Lookup Table Data" in an itemset
cc: @sravfeyn

Change to itemset

---

src/mugs.js

After a discussion with Amelia, wanted to change the text for required questions.
@amsagoff @dimagi/product

Change text for Required Checkbox

---

src/templates/markdown_help.html
src/templates/question_fieldset.html
src/templates/ui_element.html

http://manage.dimagi.com/default.asp?216968#1088780
cc: @snopoke

negative tabindex on help bubbles

---

buildmain.py
src/richText.js
tests/.jshintrc
tests/advancedItemsets.js
tests/atwho.js
tests/base.js
tests/comments.js
tests/copy-paste.js
tests/core.js
tests/databrowser.js
tests/datasources.js
tests/diffDataParent.js
tests/exporter.js
tests/formdesigner.lock.js
tests/itemset.js
tests/javaRosa.js
tests/logic.js
tests/main.js
tests/markdown.js
tests/modeliteration.js
tests/parser.js
tests/profiling.js
tests/questionTypes.js
tests/tsv.js
tests/widgets.js
tests/writer.js
tests/xml.js

Pulling this from my hackathon stuff
cc @snopoke

standardize requirejs/define

---

src/mugs.js
tests/options.js
tests/setvalue.js

This was added in sometime in the cmitfb meetings. Pulling it out here. I know that icds uses these, not sure who else does.
@snopoke

Feature flag data refs

---

src/form.js

Remove never used functions

---

src/core.js
tests/core.js

http://manage.dimagi.com/default.asp?217706
cc: @snopoke

Don't deselect mug on collapse

---

src/templates/widget_attachment_case.html
src/templates/widget_index_case.html
src/templates/widget_save_to_case.html
src/templates/widget_update_case.html

http://manage.dimagi.com/default.asp?218416
Now looks like this:
@emord 
code buddy @gcapalbo

B3 changes for save to case question

---

src/mugs.js
tests/setvalue.js

http://manage.dimagi.com/default.asp?218713
cc: @calellowitz

Don't warn on attribute references

---

src/form.js
src/intentManager.js
src/mugs.js
tests/copy-paste.js
tests/form.js

@millerdev cc: @NoahCarnahan
http://manage.dimagi.com/default.asp?220774#1105718
This removes the odk only warning at the request of @dimagi/product

Android warning

---

src/commtrack.js
tests/commtrack.js
tests/static/commtrack/balance-block.xml
tests/static/commtrack/transfer-block.xml

@esoergel @millerdev @czue 
cc @biyeun

use now() instead of /data/meta/timeEnd

---

src/templates/question_fieldset.html

http://manage.dimagi.com/default.asp?221496

Fix accordion icons

---

src/core.js
tests/core.js
tests/options.js

http://manage.dimagi.com/default.asp?221617
@emord cc @proteusvacuum

Add activity notification to keep session alive

---

src/parser.js
src/writer.js
tests/questionTypes.js

http://manage.dimagi.com/default.asp?221525
Not adding new tests as it's already tested after changing to use `util.loadXML` and the check in the parser (tests fail between commits 2 and 3)
@millerdev @orangejenny 
cc: @biyeun

Undefined xmlns

---

src/parser.js

http://manage.dimagi.com/default.asp?221525
cc: @dannyroberts

Kill xmlns warning

---

bower.json
src/main.js
src/uploader.js

Drop flash-related code. Merge along with https://github.com/dimagi/MediaUploader/pull/17
@emord

HTML5 version of YUI uploader

---

src/richText.js
tests/richText.js

http://manage.dimagi.com/default.asp?220734#1107520
http://manage.dimagi.com/default.asp?220534#1112557
cc: @dannyroberts

Popover destroy

---

src/core.js
src/form.js
src/javaRosa.js

@emord cc: @NoahCarnahan 
tracking when case properties are dragged and dropped into the form builder

adding ga tracking for case management in the form builder

---

src/javaRosa.js
tests/markdown.js
tests/static/markdown/markdown-output-value.xml

http://manage.dimagi.com/default.asp?225093
@orangejenny

don't write #form to markdown

---

src/expressionEditor.js

http://manage.dimagi.com/default.asp?225058

Advanced mode displaying #form even without flags on

---

src/fuse.js
src/templates/atwho_display.html

http://manage.dimagi.com/default.asp?224965
@emord

display #form in autocomplete

---

src/expressionEditor.js
tests/widgets.js

@orangejenny this should replace https://github.com/dimagi/Vellum/pull/638 I had fixed this the other day, but couldn't get wifi on my layover. I think the bug was double logged http://manage.dimagi.com/default.asp?225013#1133170 & http://manage.dimagi.com/default.asp?225058

normalize xpath for advanced expression editing

---

tests/databrowser.js
tests/javaRosa.js
tests/markdown.js

vellum_util -> vellumUtil

---

tests/atwho.js

https://github.com/dimagi/Vellum/pull/640#issuecomment-215449896
probably easiest by commit with whitespace ignored for the first two
@orangejenny @millerdev

Test atwho form

---

src/javaRosa.js
src/richText.js
src/util.js
src/widgets.js

http://manage.dimagi.com/default.asp?224826#1136143
@NoahCarnahan says this looks right for hebrew.

support right to left text in labels

---

src/core.js
src/form.js
src/templates/undo_alert.html
src/undomanager.js
src/window.js
tests/undomanager.js

http://manage.dimagi.com/default.asp?224963
@emord

Panel resize for undo delete

---

src/uploader.js

http://manage.dimagi.com/default.asp?224561#assign_1_224561
Introduced here: https://github.com/dimagi/Vellum/pull/634

fix uploader

---

src/databrowser.js
src/form.js

@millerdev https://github.com/dimagi/Vellum/pull/605#issuecomment-181543153

use indexBy

---

src/expressionEditor.js

http://manage.dimagi.com/default.asp?217896#1093575
https://github.com/dimagi/Vellum/pull/617#issuecomment-186309022
this bug only shows up in the new editor. I've been sitting on this fix for a few days, because I haven't had a chance to bootstrap the expression editor tests that support rich text yet
@millerdev @gcapalbo

Fix lost changes

---

src/window.js
tests/undomanager.js

@emord 
Introduced in https://github.com/dimagi/Vellum/pull/639
Would like to deploy this once it's merged. Chatted with @amsagoff and decided it isn't hotfix-worthy, but I'd rather not wait until tomorrow afternoon's deploy.

External data panel always hidden

---

src/databrowser.js
tests/databrowser.js

http://manage.dimagi.com/default.asp?226125#1139553
@orangejenny 
cc: @gcapalbo

Refresh visible data

---

src/core.js
src/form.js
src/undomanager.js

https://github.com/dimagi/Vellum/pull/639/files/13e30e30147eccd7ff6d6bd0a7e62e977f8bae3b#r61759913
@millerdev better?
Debating firing an event for when a question removal is undone, but no one would be listening for it, so it seemed like overkill.

Events for UndoManager

---

src/modeliteration.js
src/mugs.js
src/parser.js
src/util.js
tests/parser.js
tests/static/parser/repeat-with-count-as-question-only-form.xml
tests/static/writer/repeat-with-count-as-question.xml
tests/writer.js

http://manage.dimagi.com/default.asp?226243#1141660
@orangejenny 
cc: @gcapalbo

Parse/write jr:count hashtags

---

src/mugs.js
tests/questionTypes.js

http://manage.dimagi.com/default.asp?226528
`delete mug.p.apperance` doesn't work because `mug.p` is not an Object it is `MugProperties` instance.
cc @gcapalbo

remove appearance attributes for all questions that explicitly set it

---

src/javaRosa/itextBlock.js

doesn't seem that this is true anymore
@emord

remove dead comment

---

tests/questionTypes.js

@millerdev https://github.com/dimagi/Vellum/pull/657/files/0c946c43180d861855cb77e6cb285dd3b2f2e1c5#r63017481

More general tests around appearance

---

src/javaRosa/itextWidget.js
tests/javaRosa.js

http://manage.dimagi.com/default.asp?224826
@gcapalbo

Support right to left text in markdown preview

---

src/core.js
src/javaRosa/itextWidget.js
src/javaRosa/util.js

https://github.com/dimagi/Vellum/pull/662#discussion_r63203288
@gcapalbo @millerdev

pr feedback

---

src/templates/question_toolbar.html

fix mismatched markup

---

src/intentManager.js
tests/intentManager.js
tests/options.js

https://docs.google.com/document/d/13mRCH3hHBsTCLzCt2bQMILxu7e8DD-CwFdEW1DsiCyI/edit#heading=h.8t08wqk9t5yj
Adds in support for mime types supplied by HQ.
@orangejenny 
cc @esoergel

Support mime/type

---

src/databrowser.js
tests/databrowser.js
tests/options.js

http://manage.dimagi.com/default.asp?227843#1154674
Will be used to blacklist name from the databrowser. It currently shows up if you try to update the name in a form

Allow specificying invalid data browser names

---

src/javaRosa/util.js
tests/databrowser.js

@orangejenny will fix your `rtl` issue

look at form instead of opts

---

src/atwho.js
src/richText.js

`#case/thing` will bubble
`#form/realquestion` will bubble
`#form/fakequestion` will not bubble
`#caze` will not bubble
@emord

Bubble text when atwho match fails

---

src/databrowser.js
src/datasources.js
src/templates/external_sources_tree.html

https://github.com/dimagi/commcare-hq/pull/12004#issuecomment-225528836
Before
After

Display data sources error text to end user

---

src/exporter.js
tests/exporter.js
tests/static/all_question_types.tsv
tests/static/exporter/item-id.tsv
tests/static/exporter/vid-ref.tsv
tests/static/exporter/vid-ref.xml

http://manage.dimagi.com/default.asp?229818
@orangejenny

Add video and video-inline to form export

---

src/richText.js
tests/richText.js

@orangejenny fixes the html weirdness

Fix html input

---

src/javaRosa/plugin.js

Update itext overview

---

src/javaRosa/itextWidget.js
src/richText.js
tests/databrowser.js
tests/exporter.js
tests/javaRosa.js
tests/static/javaRosa/output-refs.xml
tests/static/javaRosa/test-xml-4.xml
tests/utils.js

@orangejenny Realized we never need the snapshot events, so there's no need to pass in a parameter.

remove snapshot change events

---

src/richText.js
tests/richText.js

Reverts dimagi/Vellum#679
@millerdev @orangejenny this caused double escaping of & so > would be &amp;lt; in forms

Revert "Fix html input"

---

src/mugs.js
tests/form.js

http://manage.dimagi.com/default.asp?229679
@orangejenny

Warn on any question named case (and variants)

---

bower.json
src/fuse.js

http://manage.dimagi.com/default.asp?229018
This should improve the fuzzy matching.

Better fuse config

---

src/javaRosa/itextWidget.js

Not sure why this was only for labels
buddy @snopoke

Add atwho to other itexts

---

src/databrowser.js
tests/databrowser.js
tests/options.js
tests/static/databrowser/child-ref-output-value-other-lang.xml
tests/static/databrowser/child-ref-output-value.xml
tests/static/databrowser/child-ref.xml
tests/static/databrowser/mother-ref.xml
tests/static/databrowser/preloaded-hashtags.xml

@orangejenny should match the schema that we discussed.
https://github.com/dimagi/Vellum/pull/684/commits/ab7959ea67b274b0fa04837d15bb01a22ad765b9 main change
https://github.com/dimagi/Vellum/pull/684/commits/47b8b9af3cf1c05c7dd0530d596330de7d4d85a0 fixes the display when you have three levels of hierarchy, been around for a while
buddy @NoahCarnahan

Change hashtag syntax

---

bower.json

Saw this the other day. Pretty sure it isn't used anywhere anymore
cc @snopoke

Remove when

---

src/xml.js
tests/static/xml/regexp-crashing-debug-itext-parsed.xml
tests/static/xml/regexp-crashing-debug-itext.xml
tests/xml.js

http://manage.dimagi.com/default.asp?231477
@emord cc @calellowitz

Fix XML normalization of many output values

---

src/intentManager.js
tests/static/intentManager/printing-intent.xml

http://manage.dimagi.com/default.asp?231804
@emord 
cc @kaapstorm

handle hashtags when writing intents

---

src/richText.js

http://manage.dimagi.com/default.asp?232759
@millerdev I don't have a good test/explanation for this one. Just the only difference I noticed between selecting with mouse vs hitting enter
buddy @NoahCarnahan

Add whitespace constant

---

src/richText.js

Reverts dimagi/Vellum#695
http://manage.dimagi.com/default.asp?232890
http://manage.dimagi.com/default.asp?232902
Didn't like this solution anyway, seems like it was a chrome-specific fix
@orangejenny @millerdev 
@NoahCarnahan

Revert "Add whitespace constant"

---

src/itemset.js
tests/questionTypes.js

http://manage.dimagi.com/default.asp?232708
@emord 
cc @benrudolph

Handle changing between dynamic types

---

src/databrowser.js
src/form.js
src/logic.js
tests/main.js

This brings the load time of the form in http://manage.dimagi.com/default.asp?232792 down from nearly 3 minutes to <15 seconds (on my local machine) by eliminating exponential complexity in the data browser `fixFormReferences` due to many errors in the form. It also further optimizes the logic manager by eliminating all places where it would inspect every reference known to the form builder. Probably easiest to review by commit.
@emord cc @biyeun

Optimize logic manager

---

src/logic.js
tests/logic.js

@millerdev From your other PR
buddy @czue

Fix case ref reporting to HQ

---

src/saveToCase.js
tests/saveToCase.js

@esoergel http://manage.dimagi.com/default.asp?234164

allow dash in case property

---

src/javaRosa/itext.js
src/javaRosa/plugin.js
src/mugs.js
tests/javaRosa.js

A choice without a label will cause a build error. Add that validation to vellum, so the problem gets surfaced earlier.
cc @benrudolph

Validate that choices have labels

---

bower.json

Upgrade js-xpath

---

src/javaRosa/plugin.js
src/mugs.js
src/richText.js
src/widgets.js
tests/databrowser.js
tests/static/all_question_types.tsv
tests/static/all_question_types.xml
tests/static/comments/comment-test.xml
tests/static/commtrack/balance-block.xml
tests/static/commtrack/transfer-block.xml
tests/static/core/hidden-value-in-repeat.xml
tests/static/databrowser/child-ref-output-value-other-lang.xml
tests/static/databrowser/child-ref-output-value.xml
tests/static/escapedHashtags/invalid-xpath.xml
tests/static/itemset/itemset-with-question-ref.xml
tests/static/javaRosa/itext-item-rename-group-move.xml
tests/static/javaRosa/itext-item-rename.xml
tests/static/javaRosa/output-refs.xml
tests/static/javaRosa/test-xml-4.xml
tests/static/modeliteration/case-list-iteration-with-questions.xml
tests/static/modeliteration/case-list-iteration.xml
tests/static/modeliteration/fixture-iteration.xml
tests/static/modeliteration/regular-repeat.xml
tests/static/parser/repeat-with-count-as-question-only-form.xml
tests/static/writer/repeat-noAddRemove-false.xml
tests/static/writer/repeat-with-count-as-question.xml
tests/static/writer/repeat-with-count-noAddRemove-false.xml
tests/static/writer/repeat-with-count.xml
tests/static/writer/repeat-without-count.xml
tests/utils.js

Different approach to http://manage.dimagi.com/default.asp?233084 - don't supply default labels (except for choices, where a missing label causes a build error).
cc @benrudolph

Label placeholders

---

src/atwho.js
tests/atwho.js

Jeremy mentioned this to me offhand
@snopoke

Allow dash in atwho matching

---

src/saveToCase.js
tests/saveToCase.js
tests/static/saveToCase/update_property.xml

@esoergel 
follow up to https://github.com/dimagi/Vellum/pull/705
cc @snopoke

Correctly parse case properties with dashes

---

src/less-style/inputs.less

http://manage.dimagi.com/default.asp?235175#1202735
@orangejenny This is the default for textareas in bootstrap 3
@snopoke

Change font size to the same as hq style

---

src/form.js
src/logic.js
tests/logic.js

http://manage.dimagi.com/default.asp?235138
Removes references on question deletion
@snopoke

Fix delete question

---

src/databrowser.js
src/form.js
src/logic.js
tests/databrowser.js
tests/logic.js
tests/static/databrowser/unknown-property-preloaded-hashtags.xml

Only write "valid" hashtags to the xml (where valid is a "known" hashtag conversion)
@orangejenny @snopoke

Don't write unknown case hashtags to xml

---

src/saveToCase.js
tests/saveToCase.js

http://manage.dimagi.com/default.asp?234191
cc @snopoke

fully fix save to case

---

src/escapedHashtags.js
src/xpath.js
tests/databrowser.js

follow up for https://github.com/dimagi/Vellum/pull/723

Test dict change

---

src/logic.js
tests/logic.js

http://manage.dimagi.com/default.asp?235138
@emord cc @esoergel

Fix null path in case references

---

bower.json
package.json

Some upgrades that don't seem to break anything
cc @czue

Upgrade stuff

---

src/saveToCase.js
tests/saveToCase.js

http://manage.dimagi.com/default.asp?235938#1207991
@czue

Restrict relationship in save to case

---

src/saveToCase.js
tests/saveToCase.js

@phillipm will fix the validation you ran into
buddy @czue

Fix save to case validation

---

src/modeliteration.js
tests/modeliteration.js
tests/static/modeliteration/case-list-iteration-with-questions-and-hidden-value.xml

@millerdev Uses the correct api for setvalues, and no longer puts them in the form
buddy @czue

Move model iteration's setvalues into mug

---

src/core.js
src/logic.js
tests/logic.js

depends on https://github.com/dimagi/commcare-hq/pull/12989
@emord

Fix multiple case references per question

---

src/core.js
src/expressionEditor.js
src/less-style/structure.less
src/templates/main.html
tests/widgets.js

http://manage.dimagi.com/default.asp?235825
The `_this.$f.find('.fd-content-right .fd-column').addClass('hide');` lines fix the bug, other changes are minor cleanup.

.fd-column visibility

---

src/escapedHashtags.js
src/form.js
src/xpath.js
tests/databrowser.js
tests/escapedHashtags.js
tests/logic.js

http://manage.dimagi.com/default.asp?235899
The first commit fixes the bug, the rest are optimizations and refactoring/simplification. Probably best to review commits individually.
@emord

Fix run-on hashtag

---

src/core.js
src/xml.js
tests/main.js
tests/static/xml/slow-regexp-itext.xml
tests/xml.js

http://manage.dimagi.com/default.asp?236305
Review commits individually.

Fix exponential slowdown in XML normalizer

---

src/javaRosa/plugin.js
tests/javaRosa.js

http://manage.dimagi.com/default.asp?236643#1212896
@millerdev 
buddy @czue

Fix $ escaping

---

src/javaRosa/itext.js
src/javaRosa/plugin.js
src/mugs.js
tests/javaRosa.js

http://manage.dimagi.com/default.asp?235545
Should have realized that https://github.com/dimagi/Vellum/pull/703/files?w=1#diff-fb1b9e010259d16ab20a8186e2d67b23R1510 wasn't quite the right thing to do.
I was inclined to put a `mug.validate()` at the end of `createQuestion` (https://github.com/dimagi/Vellum/blob/master/src/form.js#L884) but it looks like we don't always want validation run for new questions (see https://github.com/dimagi/Vellum/blob/master/tests/commtrack.js#L145).

Error in warning message when adding a new choice

---

src/templates/widget_index_case.html
tests/saveToCase.js

@czue http://manage.dimagi.com/default.asp?236733#1214079

Save to case fixes

---

tests/xml.js

Add comments for known XML normalization failures

---

bower.json
package.json

noticed when I was deploying new version of vellum

upgrade requirejs

---

src/core.js
src/form.js
src/logic.js
tests/form.js
tests/logic.js

http://manage.dimagi.com/default.asp?236398
Review commits individually.
@emord cc @NoahCarnahan

Fix error on label itext with multiple refs

---

src/expressionEditor.js
src/templates/xpath.html

http://manage.dimagi.com/default.asp?236572
Save button is now
- Disabled when there are no changes.
- Green when expression has changed.

Fix expression editor save button inconsistencies

---

src/javaRosa/plugin.js
src/javaRosa/util.js
tests/javaRosa.js
tests/richText.js
tests/static/javaRosa/invalid-output-ref.xml

http://manage.dimagi.com/default.asp?236968#1215641

test invalid output values

---

src/atwho.js
src/logic.js
src/util.js

@calellowitz went ahead and did this

fix case ref autocomplete analytics

---

bower.json

Tests pass locally, would prefer not to merge until https://github.com/dimagi/commcare-hq/pull/13031 is ready.

Upgrade to jQuery 2.2.0

---

bower.json

match https://github.com/dimagi/commcare-hq/pull/13252
@emord

jQuery 2.2.4

---

bower.json

because library upgrades are so fun.
I did a sanity check locally and everything looks ok

upgrade jstree & fuse

---

src/commtrack.js
tests/copy-paste.js

@esoergel I think I punted this for some reason before, but I don't remember why. It was super easy to just do it. Is there any reason not to allow this?

Change date in commtrack questions

---

src/core.js
src/ignoreButRetain.js
src/javaRosa/itextBlock.js
src/saveToCase.js
src/uploader.js
src/widgets.js

https://jquery.com/upgrade-guide/3.0/
@emord

jQuery 3 compatibility

---

src/less-style/question-props.less
src/templates/question_toolbar.html

http://manage.dimagi.com/default.asp?237504
code buddies @esoergel / @czue

respect whitespace in question comments

---

src/less-style/inputs.less

http://manage.dimagi.com/default.asp?237606
Went with the lazy option. Here's what it looks like in HQ with a small screen:
@orangejenny @emord cc @sravfeyn

Increase initial height of advanced xpath editor

---

src/widgets.js
tests/widgets.js

http://manage.dimagi.com/default.asp?236878
@emord cc @NoahCarnahan

Allow drag/drop into bool xpath widget

---

src/core.js
src/javaRosa/util.js
src/richText.js
src/xml.js
tests/copy-paste.js
tests/core.js
tests/xml.js

http://manage.dimagi.com/default.asp?236328
@orangejenny

Fix HTML escaping in question tree

---

src/atwho.js
src/form.js

@millerdev saw you had a comment on slack. I didn't change the save to case thing as that is a feature flag and I haven't looked into if HQ always uses `/data/meta/timeEnd` or if it changes it to `/rootid/meta/timeEnd`

Slash data

---

tests/form.js

@millerdev as promised https://github.com/dimagi/Vellum/pull/766/files#r81555334
buddy @czue

Add explicit test for #form transform

---

src/atwho.js

@emord cc: @dannyroberts 
One more change to vellum analytics based on feedback from @amsagoff

changing language for analytics

---

src/less-style/structure.less
src/window.js

http://manage.dimagi.com/default.asp?236113

get rid of double scroll bar in full screen mode

---

bower.json
src/atwho.js
src/core.js
src/expressionEditor.js
src/itemset.js
src/javaRosa/itextWidget.js
src/richText.js
src/saveToCase.js
src/widgets.js

http://manage.dimagi.com/default.asp?238911
Includes https://github.com/ichord/At.js/pull/438 via [millerdev/At.js#master](https://github.com/millerdev/At.js/tree/master)
A lot of this is cleanup that I did while troubleshooting the bug. I had been putting off blaming the problem on At.js until I eliminated everything else that could have caused the issue.
Best to review each commit individually.
@emord

Fix lookup table menu

---

src/javaRosa/plugin.js
tests/javaRosa.js

http://manage.dimagi.com/default.asp?238735
@orangejenny cc @proteusvacuum

Fix validation condition error that won't go away

---

src/expressionEditor.js

http://manage.dimagi.com/default.asp?240030

hide simple mode button when simple mode isn't available

---

src/core.js
src/jquery-extensions.js
src/richText.js
tests/richText.js

Experiment discussed with @amsagoff  So that we can determine whether or not to keep this as a feature, it adds events that record when people a) see the popover and b) click on the link in the popover.

Highlight easy reference in tree

---

src/richText.js
src/templates/easy_reference_popover.html

https://github.com/dimagi/Vellum/pull/779#pullrequestreview-6147456
Not going to do anything about the analytics calls right now, though I agree they're getting increasingly disorganized.
@emord

Use template for easy reference popover

---

README.md

Same form, just updated with new UI.
now with more panes but same number of scroll bars

update image in readme

---

tests/richText.js

Test for https://github.com/dimagi/Vellum/pull/779
@emord

Add test for 'show in question list' link

---

src/core.js
src/templates/find_usages.html

@phillipm 
https://github.com/dimagi/Vellum/pull/787#issuecomment-258323576
This enables clicking on one of the references displayed in the find usages table and going to the question that references that.

Follow click on table to reference

---

src/expressionEditor.js
src/richText.js
tests/widgets.js

http://manage.dimagi.com/default.asp?240388
The test took way long to get right!
@emord cc @nickpell

Activate advanced xpath editor save on change

---

src/analytics.js
src/atwho.js
src/copy-paste.js
src/core.js
src/expressionEditor.js
src/javaRosa/plugin.js
src/richText.js
src/widgets.js

Moving out analytics into its own file. Having it sprinkled throughout the code was annoying me.
@millerdev @orangejenny 

Move analytics to its own file

---

src/core.js
src/less-style/modals.less

@czue bug you mentioned
That's pretty ugly, so making find usages full screen for now

find usages should be full screen

---

src/databrowser.js
tests/databrowser.js
tests/static/databrowser/ignore-rich-text.xml

Noticed while trying to reproduce http://manage.dimagi.com/default.asp?241253
@emord cc @nickpell

Fix drag/drop case property with rich text off

---

bower.json

Bump jQuery 3.1.0 to 3.1.1

---

src/core.js

@proteusvacuum  http://manage.dimagi.com/default.asp?241263#1245311

scroll find usages

---

src/core.js
src/less-style/structure.less
src/templates/main.html

Rename question tree to form name

---

src/form.js
tests/form.js

http://manage.dimagi.com/default.asp?241253
@emord or @orangejenny

Load case hashtags on enable easy references

---

src/atwho.js
src/core.js
src/less-style/inputs.less
src/templates/find_usages.html
src/templates/find_usages_search.html

search find usages

---

src/atwho.js
src/core.js
src/javaRosa/plugin.js
src/less-style/structure.less

Add context to question properties window

---

src/form.js
tests/datasources.js
tests/form.js

http://manage.dimagi.com/default.asp?241253
@orangejenny or @emord

Do not set form.hasCaseHashtags prematurely

---

src/core.js
src/javaRosa/itextWidget.js
tests/core.js
tests/javaRosa.js

http://manage.dimagi.com/default.asp?241935
Plus some tech debt.
@orangejenny

Refresh mug name on display mug properties

---

src/core.js
src/less-style/inputs.less
src/templates/find_usages_search.html

http://manage.dimagi.com/default.asp?242019 @proteusvacuum

Don't reload on enter find usages

---

src/core.js

https://github.com/dimagi/Vellum/commit/65cccf5d3ccc676cedc05b8d89247b3e3293fb68
luckily default is 0
@orangejenny

add timeout to debounce

---

src/templates/widget_index_case.html

@proteusvacuum http://manage.dimagi.com/default.asp?242247

better naming

---

src/templates/multimedia_existing_text.html

http://manage.dimagi.com/default.asp?242260
@gcapalbo

Shorten button text

---

src/mugs.js
tests/mugs.js

http://manage.dimagi.com/default.asp?242423
@orangejenny or @emord

Error on "meta" question ID.

---

src/richText.js
tests/richText.js

For more consistent editing experience.
@emord

Do not use zero-width spaces in rich text

---

src/parser.js

@emord @millerdev 
cc @nickpell 
for https://github.com/dimagi/commcare-hq/pull/14112

remove error for empty data block

---

src/javaRosa/itextBlock.js
src/javaRosa/itextWidget.js
tests/javaRosa.js

http://manage.dimagi.com/default.asp?243325
Should have been removed in fff0984be3ee426a623fc14071dad4ee69c4dee1

Remove non-existent event handler

---

src/expressionEditor.js
tests/widgets.js

http://manage.dimagi.com/default.asp?243357

Activate expression editor save button on remove simple expression row

---

src/exporter.js
tests/exporter.js
tests/questionTypes.js
tests/static/all_question_types.tsv
tests/static/all_question_types.xml
tests/static/exporter/item-id.tsv
tests/static/exporter/vid-ref.tsv

Add hint text, help text and comment text to TSV export.
@millerdev @nickpell

[GS Efficiency] export hint help comment

---

src/richText.js
tests/richText.js

http://manage.dimagi.com/default.asp?243816

delay on easy reference popover

---

src/richText.js
tests/richText.js

http://manage.dimagi.com/default.asp?244242
@orangejenny cc @benrudolph

Fix popover bug causing expression editor fail

---

src/datasources.js

Open to suggestions to improve this even more.
@emord @snopoke

Improve data sources schema docs

---

README.md

@orangejenny let me know if this isn't the right place/language for this.

add bower/npm update to readme

---

README.md

the other one at least, didn't work for me.

proper syntax for grep

---

src/logic.js
src/saveToCase.js
tests/logic.js
tests/saveToCase.js
tests/static/logic/save_to_case.xml
tests/static/saveToCase/case_type_property.xml
tests/static/saveToCase/close_property.xml
tests/static/saveToCase/create_2_property.xml
tests/static/saveToCase/create_property.xml
tests/static/saveToCase/index_property.xml
tests/static/saveToCase/logic_test.xml
tests/static/saveToCase/update_property.xml

add case references from save to case questions

---

src/logic.js
tests/logic.js

https://github.com/dimagi/commcare-hq/pull/14221#issuecomment-267066954
@emord

Do not slice hashtag off of case references

---

src/datasources.js
src/richText.js
tests/options.js
tests/richText.js

The other half of https://github.com/dimagi/commcare-hq/pull/14718 - should be safe to merge in any order.
@calellowitz @emord

Case property descriptions

---

src/richText.js
tests/richText.js

Happens when pasting text copied from Google Sheets.
http://manage.dimagi.com/default.asp?245729

Fix pasted styles leaking into editor content

---

src/mugs.js
tests/questionTypes.js

http://manage.dimagi.com/default.asp?245643

Remove required on change question type to Trigger

---

src/core.js
src/form.js
src/less-style/tree-content.less
src/logic.js
src/mugs.js
src/templates/undo_alert.html
src/undomanager.js
tests/logic.js
tests/mugs.js
tests/undomanager.js

First part of http://manage.dimagi.com/default.asp?242658
Best reviewed by commit 🐠 

Make undo alert red when deleted questions are still referenced

---

src/core.js
src/form.js
src/logic.js
tests/logic.js

Not thrilled with the look, but I suppose it will get your attention. Would accept help with style improvements.
Part 2 of ﻿﻿http://manage.dimagi.com/default.asp?242658

Save button warning on hover with errors in form

---

src/expressionEditor.js
tests/expressionEditor.js
tests/main.js

Show nicer error in expression editor when expression is not valid XPath.
Related to http://manage.dimagi.com/default.asp?248097

Unescape invalid XPath before validation

---

src/javaRosa/itext.js
src/javaRosa/plugin.js
src/logic.js
tests/javaRosa.js
tests/modeliteration.js

Refactor in preparation for another change coming soon. Have wanted to do this forever to eliminate that nasty regex find/replace in `javaRosa.handleMugRename`.

Move javaRosa logic updates into logic manager

---

src/core.js

@orangejenny this is into your other PR
calculate attrs only come up for hidden values so i think it might be nice to have this up at the top for those

move calculate condition to basic

---

src/core.js
tests/questionTypes.js

https://manage.dimagi.com/default.asp?249190
PR into https://github.com/dimagi/Vellum/pull/847
Would like to get this into today's deploy.
@millerdev / @emord 
cc @dannyroberts

Add choice for existing selects

---

src/less-style/tree-content.less

@biyeun any objections to this? Suggestion from @benrudolph to make the "Add Choice" look less like a choice itself.

Bump add choice left

---

src/core.js

https://manage.dimagi.com/default.asp?249202

Always remove popover on save

---

src/uploader.js

https://manage.dimagi.com/default.asp?249821
@millerdev

fix template

---

src/mugs.js
tests/copy-paste.js

https://manage.dimagi.com/default.asp?248770
@emord @orangejenny cc @esoergel

Fix calculate condition on text after paste

---

src/core.js

add fullscreen callback

---

src/core.js
tests/richText.js

@emord @orangejenny cc @benrudolph

Expand parent groups when showing in tree

---

bower.json

@emord 
Would like to get into today's deploy.

bump jstree-actions

---

src/less-style/structure.less
src/less-style/tree-content.less

Small request from @millerdev .  Seemed reasonable to me. @biyeun does this work for you?
Before
After

Shrink app properties head

---

src/core.js
tests/questionTypes.js

https://manage.dimagi.com/default.asp?252529

+Add Choice for MC questions does not work if another question is selected

---

src/core.js

allow custom load options

---

src/core.js

https://manage.dimagi.com/default.asp?252794

Generate ids when choices are added repeatedly

---

src/form.js
src/logic.js
tests/datasources.js
tests/static/datasources/unknown-case-property.xml

https://manage.dimagi.com/default.asp?252531
@emord

Validate external refs on load data sources

---

src/logic.js
tests/datasources.js
tests/static/datasources/unknown-case-property.xml

https://manage.dimagi.com/default.asp?252531 - I found a bug in the previous fix while re-testing on a real app.
@emord

Validate broken references in itext

---

src/javaRosa/plugin.js
tests/javaRosa.js

https://manage.dimagi.com/default.asp?248877

Always use first language in options as default

---

src/core.js
src/javaRosa/itextWidget.js
src/widgets.js
tests/core.js
tests/utils.js

https://manage.dimagi.com/default.asp?250360

Fix auto question ID on delete existing value

---

src/databrowser.js
src/datasources.js
tests/databrowser.js
tests/datasources.js

Use index XPath on drag/drop related index node

---

src/javaRosa/itext.js
src/javaRosa/plugin.js
tests/javaRosa.js
tests/static/javaRosa/single-lang-select.xml

https://manage.dimagi.com/default.asp?252146

Fix error on choice when a language is not defined

---

src/intentManager.js
src/mugs.js
tests/intentManager.js

https://manage.dimagi.com/default.asp?237500

Validate that callout question IDs are unique

---

src/richText.js
tests/richText.js

https://manage.dimagi.com/default.asp?254549

Replace zero-width spaces from CKEditor

---

src/templates/question_toolbar.html

Match https://github.com/dimagi/commcare-hq/pull/16430
@emord

Add caret to section toggler

---

src/core.js
src/javaRosa/itext.js
src/javaRosa/plugin.js
src/less-style/modals.less
src/less-style/tree-content.less
src/mugs.js
src/writer.js
tests/mugs.js
tests/static/mugs/blank-choice.xml
tests/utils.js
tests/writer.js

Trying to make this situation better: https://manage.dimagi.com/default.asp?255685
Review by commit 🐠 
729799c is not really part of the fix, but solves a long-standing annoyance I had with the view source XML feature.

Improve handling of choice with blank value

---

src/core.js
src/logic.js
tests/form.js
tests/richText.js

https://manage.dimagi.com/default.asp?256986

Remove mug reference errors on delete mug

---

src/itemset.js
tests/itemset.js
tests/static/itemset/itemset-sort.xml

https://manage.dimagi.com/default.asp?257233

Add a sort field to itemset

---

src/richText.js

https://manage.dimagi.com/default.asp?258714
Not even going to attempt a test for this one.

Fix bug in drag/drop rich text bubble

---

src/itemset.js
tests/itemset.js
tests/static/itemset/filter-with-case-property.xml

https://manage.dimagi.com/default.asp?258835

Fix in itemset filter parsing bug.

---

src/uploader.js

https://manage.dimagi.com/default.asp?258995

Render template to get translation

---

src/saveToCase.js
tests/saveToCase.js
tests/static/saveToCase/two-same-name.xml

https://manage.dimagi.com/default.asp?257017
@emord

Do not drop setvalues for other mugs with same name

---

src/javaRosa/itextWidget.js

https://manage.dimagi.com/default.asp?258455

Fix markdown toggle switch disappearing

---

src/form.js
src/richText.js
tests/richText.js

https://manage.dimagi.com/default.asp?259925

Fix rich text error due to bad hashtag expression

---

src/parser.js
tests/parser.js

https://manage.dimagi.com/default.asp?258232

Fix choice value with HTML special chars

---

src/atwho.js
src/base.js
src/commander.js
src/copy-paste.js
src/core.js
src/less-style/inputs.less
src/less-style/structure.less
src/main.js
src/templates/commander.html
src/templates/main.html
src/util.js
tests/commander.js
tests/main.js

Vellum Commander

---

src/commander.js
tests/commander.js

Important to get this in before next HQ deploy.

Commander: ensure saved before select question

---

src/less-style/inputs.less
src/templates/commander.html

Tweak commander styles

---

src/commander.js
tests/commander.js

Make it easier to auto-complete items by improving relevance of the first item in the list to the typed command.

Improve autocomplete sorting

---

.bowerrc
src/base.js
src/core.js
src/main.js
src/remoteRequest.js
src/util.js
tests/main.js
tests/options.js
tests/remoteRequest.js
tests/static/remoteRequest/remoteRequest.xml

spec: https://docs.google.com/document/d/1x1xz2N7I_kTUjM4dFx31vt9EuzPrOWzSojnWD062XDs
The second commit fixes an unrelated test issue.
@orangejenny @emord cc @ctsims

Add Remote Request question type

---

bower.json

```
$ npm install -g npm-check-updates
$ npm-check-updates --packageManager bower
```
Tests pass locally, sanity tested in browser (bubbles, xml viewing, markdown).

Library upgrades

---

src/commander.js
src/core.js
src/remoteRequest.js
tests/remoteRequest.js

Fixes for feedback from #924 and also some bug fixes.
Review by commit 🐠 
@orangejenny

Remote Request feedback

---

bower.json

Upgrade jstree-actions

---

Makefile
index.html
src/core.js
src/datasources.js
src/form.js
src/intentManager.js
src/javaRosa/plugin.js
tests/atwho.js
tests/databrowser.js
tests/formdesigner.lock.js
tests/options.js
tests/questionTypes.js
tests/richText.js
tests/static/ignoreButRetain/renamed.xml

Yesterday's [code quality challenge](https://forum.codequalitychallenge.com/t/day-2-nuke-todo-comments/375/58). Removed 16 obsolete or easily actionable TODO comments. There may be more that fit this criteria, but I ran out of time. Only 56 more to go (not gonna do it).

Todo removal

---

src/parser.js
tests/parser.js
tests/static/parser/accent-char-in-path.xml

https://manage.dimagi.com/default.asp?269812
@emord @jmtroth0

Fix error on load form with accented question id

---

src/mugs.js
tests/diffDataParent.js

A question's data parent must now be (in) the same repeat group that is the nearest repeat control ancestor of the question. Previously questions in repeat groups could not have a custom data parent.
@emord @jmtroth0 @ctsims

Allow setting data parent of question in repeat group

---

src/core.js
src/databrowser.js
src/javaRosa/plugin.js

https://manage.dimagi.com/default.asp?269097
@orangejenny @emord cc @gcapalbo

Fix drag/drop date question into itext widget

---

src/mugs.js
tests/form.js

https://manage.dimagi.com/default.asp?272602
@orangejenny @emord cc @gcapalbo

Warn on Question ID value of "registration"

---

src/javaRosa/plugin.js

https://manage.dimagi.com/default.asp?272945
@emord @orangejenny cc @calellowitz

Hide "Validation Error Message" when using javaRosa

---

src/core.js
src/exporter.js
src/mugs.js
src/parser.js
tests/logic.js
tests/parser.js
tests/questionProperties.js
tests/static/parser/required.xml

I'm mainly interested in this point on feedback on both UX and whether or not I found all the things I needed to change.
Right now it adds an input box in the logic section for the required condition. If you enter anything while it isn't marked "required" then it will warn you off. I was thinking of making it so the box only appeared if required was checked, but I wasn't sure about how to do that or if it was that much better.
https://trello.com/c/pb9LDmk8/6-make-it-possible-to-define-a-function-for-required-on-a-question-jen
Not sure who usually reviews vellum stuff --> @millerdev @orangejenny buddy: @snopoke 
I definitely recommend `w=1`, but probably can 🏛 . Only commits 2fac576, 685e7ea, and 05a8363 do anything

required condition

---

src/mugs.js
tests/parser.js

https://manage.dimagi.com/default.asp?282567#1525576

"legal" -> "valid"

---

src/databrowser.js
src/templates/external_sources_tree.html

Part of https://dimagi-dev.atlassian.net/browse/HI-172
Refinement of https://github.com/dimagi/Vellum/pull/946
@millerdev / @dannyroberts

Show app properties error message when possible

---

src/util.js

https://dimagi-dev.atlassian.net/browse/HI-188
@millerdev @emord

Removed Panjabi from list of right to left langs

---

lib/SaveButton.js

Goes with https://github.com/dimagi/commcare-hq/pull/22679
At this point `lib/SaveButton` and HQ's `main.js` have diverged a bit. Not going to deal with that right now.
@emord 
fyi @ohmegasquared @dimagi/product

Update save button color

---

src/parser.js
tests/form.js
tests/static/form/missing-value.xml

Not sure how [a form gets into this state](https://dimagi-dev.atlassian.net/browse/HI-596), but we can at least attempt to handle it gracefully when it happens, allowing the user to fix the error and move on.
@orangejenny @sravfeyn

Gracefully load choice with missing value node

---

README.md

Add vocabulary section to readme [skip ci]

---

src/less-style/structure.less
src/templates/main.html
src/window.js

Slightly different approach to https://github.com/dimagi/Vellum/pull/960 which passed tests on travis but is failing locally. This one is passing tests locally.

Updated approach to scrolling languages menu

---

README.md

https://github.com/dimagi/commcare-hq/pull/25919#discussion_r345943774

Updated README to stop referencing the exchange [ci skip]

---

package.json
yarn.lock

Upgrade Mardown-it on Vellum as we are upgrading the version on HQ also https://github.com/dimagi/commcare-hq/pull/28922
This won't change anything for user.
QA Plan would be same as we are doing in HQ https://github.com/dimagi/commcare-hq/pull/28922
The changes are pretty safe and have been tested on local and staging.
Rolling back the version would do the trick.

Bump markdown-it version

---

package.json
yarn.lock

This PR updates grunt version in Vellum same as https://github.com/dimagi/commcare-hq/pull/28889

Update grunt version

---

index.html
package.json
yarn.lock

Also fix benign typo in index.html

Fix equivalent-xml version

---

src/xml.js
tests/core.js
tests/xml.js

Fixes: Ampersand in question ID bug
Jira: [SAAS-10981](https://dimagi-dev.atlassian.net/browse/SAAS-10981)
Correctly represents question IDs with '&' characters
New tests added that confirm the existing bug and confirms the fix. 
QA Passed:
https://dimagi-dev.atlassian.net/browse/QA-3281
Added new tests and confident the fix is safe (existing tests pass).

Fix ampersand question ID bug

---

.jshintrc
src/core.js
src/javaRosa/itextWidget.js
src/javaRosa/plugin.js
src/richText.js
src/xml.js
tests/core.js
tests/javaRosa.js
tests/utils.js

[Jira ticket](https://dimagi-dev.atlassian.net/browse/SAAS-12756) (PR in ticket)

Sanitize formbuilder input

---

src/datasources.js
tests/options.js
tests/richText.js

Note: The changes here are already present in HQ and have been deployed. They were added directly to the compile JS.
Porting changes from https://github.com/dimagi/commcare-hq/pull/33401
Also added a test and a small change to remove extra whitespace.
See https://github.com/dimagi/commcare-hq/pull/33401
Added in this PR
None
See https://github.com/dimagi/commcare-hq/pull/33401
Also, it's already deployed.

case prop description word wrap

---

src/commcareConnect.js
tests/commcareConnect.js
tests/static/commcareConnect/learn_module.xml

Jira: https://dimagi-dev.atlassian.net/browse/CCPC-119
Add 'Display Condition' to the Learn Module mug.
CommCare Connect
Tests updated
None
Tested locally. Changes only affect the 'commcareConnect' plugin.

add 'display condition' for Learn Module question type

---

src/core.js
src/exporter.js

[Jira ticket](https://dimagi-dev.atlassian.net/browse/SAAS-15070)
[other PR](https://github.com/dimagi/private-Vellum/pull/20)
See other PR

Sanitize comments

---

src/core.js
src/mugs.js
src/parser.js
tests/exporter.js
tests/questionTypes.js
tests/static/all_question_types.tsv
tests/static/all_question_types.xml

Link to ticket [here](https://dimagi.atlassian.net/browse/SC-3346).
Related PR that creates relevant feature flag can be found [here](https://github.com/dimagi/commcare-hq/pull/34087).
This PR is part of a larger change set in which micro case images are added to CommCare behind a new feature flag.
`CASE_MICRO_IMAGE`
A new "Micro-Image" question type is added under the "Multimedia Capture" group:
The added code sits behind the new feature flag, and so will only execute if the given FF is enabled.
Automated tests exist to ensure properties of new `MicroImage` mug type are correct.
None

Add Micro Image Mug

---

src/commcareConnect.js
src/commtrack.js
src/core.js
src/databrowser.js
src/javaRosa/plugin.js
src/less-style/tree-content.less
src/mugs.js
src/richText.js
src/templates/commander.html
src/templates/external_sources_tree.html
src/templates/multimedia_modal.html
src/templates/question_toolbar.html
tests/intentManager.js
tests/options.js
tests/richText.js

This PR includes CSS class changes needed to upgrade frontawesome on HQ to the latest version
Here is the PR for HQ: https://github.com/dimagi/commcare-hq/pull/34007
possibly?
These changes are on staging to test their effectiveness
testing changes on staging while QA is ongoing for other features

Vellum icon renames for changes with new fontawesome

---

.github/workflows/codeql.yml

https://dimagi.atlassian.net/browse/USH-5721
Same as https://github.com/dimagi/commcare-hq/pull/36212 and https://github.com/dimagi/commcare-cloud/pull/6540
Affects PR build only

Run CodeQL on (all) PRs

---

src/core.js
src/mugs.js
src/parser.js
tests/questionTypes.js
tests/static/all_question_types.tsv
tests/static/all_question_types.xml

[Jira Ticket](https://dimagi.atlassian.net/browse/USH-5366)
One of 3 PRs for creating a new Document upload question
[HQ PR](https://github.com/dimagi/commcare-hq/pull/36034)
core PR (will update when I open it)
technically none but to use it in web apps you need [Webapps Upload Questions](https://staging.commcarehq.org/hq/flags/edit/web_apps_upload_questions/)
Users will now be able to upload a greater variety of file types through a new Document Upload multimedia question (docx, xlsx, txt, rtf, html, msg, pdf)
[QA ticket](https://dimagi.atlassian.net/browse/QA-7634)

Add document upload question mug

---

README.md

I didn't find it obvious from the README that the testserver was also the way to run Vellum without dealing with setting it up in HQ.  Just trying to clarify that a bit, feel free to make suggestions, as I felt clumsy with the vocabulary.
README only

Clarify dev server instructions in readme

---

package.json
yarn.lock

https://dimagi.atlassian.net/browse/SAAS-17773
The 6.0.0 usage of serialize-javascript is only in mocha, which is for tests. If tests pass, this is fine.
No

Use serialize-javascript 6.0.2

---

package.json
yarn.lock

https://dimagi.atlassian.net/browse/SAAS-17970
Bumps pbkdf2 in js-xpath and that is it.
Apart from tests, I can deploy this to staging just to be sure things look good. **Update** looks good on staging
js-xpath is well tested.
No

Bump js-xpath to 0.0.9

---

package.json
yarn.lock

Updates form-data to a newer version, it is a transitive dependency from less.

Pin form-data to a newer version
